// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/authelia/authelia/v4/internal/duo (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -package mocks -destination duo.go -mock_names Provider=MockDuo github.com/authelia/authelia/v4/internal/duo Provider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	url "net/url"
	reflect "reflect"

	duo "github.com/authelia/authelia/v4/internal/duo"
	session "github.com/authelia/authelia/v4/internal/session"
	gomock "go.uber.org/mock/gomock"
)

// MockDuo is a mock of Provider interface.
type MockDuo struct {
	ctrl     *gomock.Controller
	recorder *MockDuoMockRecorder
	isgomock struct{}
}

// MockDuoMockRecorder is the mock recorder for MockDuo.
type MockDuoMockRecorder struct {
	mock *MockDuo
}

// NewMockDuo creates a new mock instance.
func NewMockDuo(ctrl *gomock.Controller) *MockDuo {
	mock := &MockDuo{ctrl: ctrl}
	mock.recorder = &MockDuoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDuo) EXPECT() *MockDuoMockRecorder {
	return m.recorder
}

// AuthCall mocks base method.
func (m *MockDuo) AuthCall(ctx duo.Context, userSession *session.UserSession, values url.Values) (*duo.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthCall", ctx, userSession, values)
	ret0, _ := ret[0].(*duo.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthCall indicates an expected call of AuthCall.
func (mr *MockDuoMockRecorder) AuthCall(ctx, userSession, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthCall", reflect.TypeOf((*MockDuo)(nil).AuthCall), ctx, userSession, values)
}

// Call mocks base method.
func (m *MockDuo) Call(ctx duo.Context, userSession *session.UserSession, values url.Values, method, path string) (*duo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", ctx, userSession, values, method, path)
	ret0, _ := ret[0].(*duo.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Call indicates an expected call of Call.
func (mr *MockDuoMockRecorder) Call(ctx, userSession, values, method, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockDuo)(nil).Call), ctx, userSession, values, method, path)
}

// PreAuthCall mocks base method.
func (m *MockDuo) PreAuthCall(ctx duo.Context, userSession *session.UserSession, values url.Values) (*duo.PreAuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreAuthCall", ctx, userSession, values)
	ret0, _ := ret[0].(*duo.PreAuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreAuthCall indicates an expected call of PreAuthCall.
func (mr *MockDuoMockRecorder) PreAuthCall(ctx, userSession, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreAuthCall", reflect.TypeOf((*MockDuo)(nil).PreAuthCall), ctx, userSession, values)
}
