// Code generated by MockGen. DO NOT EDIT.
// Source: authelia.com/provider/oauth2 (interfaces: Storage)
//
// Generated by this command:
//
//	mockgen -package mocks -destination oauth2_storage.go -mock_names Storage=MockOAuth2Storage authelia.com/provider/oauth2 Storage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	oauth2 "authelia.com/provider/oauth2"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuth2Storage is a mock of Storage interface.
type MockOAuth2Storage struct {
	ctrl     *gomock.Controller
	recorder *MockOAuth2StorageMockRecorder
}

// MockOAuth2StorageMockRecorder is the mock recorder for MockOAuth2Storage.
type MockOAuth2StorageMockRecorder struct {
	mock *MockOAuth2Storage
}

// NewMockOAuth2Storage creates a new mock instance.
func NewMockOAuth2Storage(ctrl *gomock.Controller) *MockOAuth2Storage {
	mock := &MockOAuth2Storage{ctrl: ctrl}
	mock.recorder = &MockOAuth2StorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuth2Storage) EXPECT() *MockOAuth2StorageMockRecorder {
	return m.recorder
}

// ClientAssertionJWTValid mocks base method.
func (m *MockOAuth2Storage) ClientAssertionJWTValid(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientAssertionJWTValid", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClientAssertionJWTValid indicates an expected call of ClientAssertionJWTValid.
func (mr *MockOAuth2StorageMockRecorder) ClientAssertionJWTValid(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientAssertionJWTValid", reflect.TypeOf((*MockOAuth2Storage)(nil).ClientAssertionJWTValid), arg0, arg1)
}

// GetClient mocks base method.
func (m *MockOAuth2Storage) GetClient(arg0 context.Context, arg1 string) (oauth2.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", arg0, arg1)
	ret0, _ := ret[0].(oauth2.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockOAuth2StorageMockRecorder) GetClient(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockOAuth2Storage)(nil).GetClient), arg0, arg1)
}

// SetClientAssertionJWT mocks base method.
func (m *MockOAuth2Storage) SetClientAssertionJWT(arg0 context.Context, arg1 string, arg2 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetClientAssertionJWT", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetClientAssertionJWT indicates an expected call of SetClientAssertionJWT.
func (mr *MockOAuth2StorageMockRecorder) SetClientAssertionJWT(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetClientAssertionJWT", reflect.TypeOf((*MockOAuth2Storage)(nil).SetClientAssertionJWT), arg0, arg1, arg2)
}
