// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/authelia/authelia/v4/internal/oidc (interfaces: ClaimsStrategy)
//
// Generated by this command:
//
//	mockgen -package mocks -destination oidc_claims_strategy.go -mock_names ClaimsStrategy=MockClaimsStrategy github.com/authelia/authelia/v4/internal/oidc ClaimsStrategy
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	oauth2 "authelia.com/provider/oauth2"
	oidc "github.com/authelia/authelia/v4/internal/oidc"
	gomock "go.uber.org/mock/gomock"
)

// MockClaimsStrategy is a mock of ClaimsStrategy interface.
type MockClaimsStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockClaimsStrategyMockRecorder
	isgomock struct{}
}

// MockClaimsStrategyMockRecorder is the mock recorder for MockClaimsStrategy.
type MockClaimsStrategyMockRecorder struct {
	mock *MockClaimsStrategy
}

// NewMockClaimsStrategy creates a new mock instance.
func NewMockClaimsStrategy(ctrl *gomock.Controller) *MockClaimsStrategy {
	mock := &MockClaimsStrategy{ctrl: ctrl}
	mock.recorder = &MockClaimsStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClaimsStrategy) EXPECT() *MockClaimsStrategyMockRecorder {
	return m.recorder
}

// HydrateAccessTokenClaims mocks base method.
func (m *MockClaimsStrategy) HydrateAccessTokenClaims(ctx oidc.ClaimsStrategyContext, strategy oauth2.ScopeStrategy, client oidc.Client, scopes, claims oauth2.Arguments, requests map[string]*oidc.ClaimRequest, detailer oidc.UserDetailer, requested, updated time.Time, original, extra map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HydrateAccessTokenClaims", ctx, strategy, client, scopes, claims, requests, detailer, requested, updated, original, extra)
	ret0, _ := ret[0].(error)
	return ret0
}

// HydrateAccessTokenClaims indicates an expected call of HydrateAccessTokenClaims.
func (mr *MockClaimsStrategyMockRecorder) HydrateAccessTokenClaims(ctx, strategy, client, scopes, claims, requests, detailer, requested, updated, original, extra any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HydrateAccessTokenClaims", reflect.TypeOf((*MockClaimsStrategy)(nil).HydrateAccessTokenClaims), ctx, strategy, client, scopes, claims, requests, detailer, requested, updated, original, extra)
}

// HydrateClientCredentialsUserInfoClaims mocks base method.
func (m *MockClaimsStrategy) HydrateClientCredentialsUserInfoClaims(ctx oidc.ClaimsStrategyContext, client oidc.Client, original, extra map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HydrateClientCredentialsUserInfoClaims", ctx, client, original, extra)
	ret0, _ := ret[0].(error)
	return ret0
}

// HydrateClientCredentialsUserInfoClaims indicates an expected call of HydrateClientCredentialsUserInfoClaims.
func (mr *MockClaimsStrategyMockRecorder) HydrateClientCredentialsUserInfoClaims(ctx, client, original, extra any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HydrateClientCredentialsUserInfoClaims", reflect.TypeOf((*MockClaimsStrategy)(nil).HydrateClientCredentialsUserInfoClaims), ctx, client, original, extra)
}

// HydrateIDTokenClaims mocks base method.
func (m *MockClaimsStrategy) HydrateIDTokenClaims(ctx oidc.ClaimsStrategyContext, strategy oauth2.ScopeStrategy, client oidc.Client, scopes, claims oauth2.Arguments, requests map[string]*oidc.ClaimRequest, detailer oidc.UserDetailer, requested, updated time.Time, original, extra map[string]any, implicit bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HydrateIDTokenClaims", ctx, strategy, client, scopes, claims, requests, detailer, requested, updated, original, extra, implicit)
	ret0, _ := ret[0].(error)
	return ret0
}

// HydrateIDTokenClaims indicates an expected call of HydrateIDTokenClaims.
func (mr *MockClaimsStrategyMockRecorder) HydrateIDTokenClaims(ctx, strategy, client, scopes, claims, requests, detailer, requested, updated, original, extra, implicit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HydrateIDTokenClaims", reflect.TypeOf((*MockClaimsStrategy)(nil).HydrateIDTokenClaims), ctx, strategy, client, scopes, claims, requests, detailer, requested, updated, original, extra, implicit)
}

// HydrateUserInfoClaims mocks base method.
func (m *MockClaimsStrategy) HydrateUserInfoClaims(ctx oidc.ClaimsStrategyContext, strategy oauth2.ScopeStrategy, client oidc.Client, scopes, claims oauth2.Arguments, requests map[string]*oidc.ClaimRequest, detailer oidc.UserDetailer, requested, updated time.Time, original, extra map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HydrateUserInfoClaims", ctx, strategy, client, scopes, claims, requests, detailer, requested, updated, original, extra)
	ret0, _ := ret[0].(error)
	return ret0
}

// HydrateUserInfoClaims indicates an expected call of HydrateUserInfoClaims.
func (mr *MockClaimsStrategyMockRecorder) HydrateUserInfoClaims(ctx, strategy, client, scopes, claims, requests, detailer, requested, updated, original, extra any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HydrateUserInfoClaims", reflect.TypeOf((*MockClaimsStrategy)(nil).HydrateUserInfoClaims), ctx, strategy, client, scopes, claims, requests, detailer, requested, updated, original, extra)
}

// MergeAccessTokenAudienceWithIDTokenAudience mocks base method.
func (m *MockClaimsStrategy) MergeAccessTokenAudienceWithIDTokenAudience() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeAccessTokenAudienceWithIDTokenAudience")
	ret0, _ := ret[0].(bool)
	return ret0
}

// MergeAccessTokenAudienceWithIDTokenAudience indicates an expected call of MergeAccessTokenAudienceWithIDTokenAudience.
func (mr *MockClaimsStrategyMockRecorder) MergeAccessTokenAudienceWithIDTokenAudience() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeAccessTokenAudienceWithIDTokenAudience", reflect.TypeOf((*MockClaimsStrategy)(nil).MergeAccessTokenAudienceWithIDTokenAudience))
}

// ValidateClaimsRequests mocks base method.
func (m *MockClaimsStrategy) ValidateClaimsRequests(ctx oidc.ClaimsStrategyContext, strategy oauth2.ScopeStrategy, client oidc.Client, requests *oidc.ClaimsRequests) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateClaimsRequests", ctx, strategy, client, requests)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateClaimsRequests indicates an expected call of ValidateClaimsRequests.
func (mr *MockClaimsStrategyMockRecorder) ValidateClaimsRequests(ctx, strategy, client, requests any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateClaimsRequests", reflect.TypeOf((*MockClaimsStrategy)(nil).ValidateClaimsRequests), ctx, strategy, client, requests)
}
