// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/authelia/authelia/v4/internal/oidc (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package mocks -destination oidc_client.go -mock_names Client=MockOIDCClient github.com/authelia/authelia/v4/internal/oidc Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	url "net/url"
	reflect "reflect"
	time "time"

	oauth2 "authelia.com/provider/oauth2"
	jose "authelia.com/provider/oauth2/token/jose"
	authentication "github.com/authelia/authelia/v4/internal/authentication"
	authorization "github.com/authelia/authelia/v4/internal/authorization"
	oidc "github.com/authelia/authelia/v4/internal/oidc"
	gomock "go.uber.org/mock/gomock"
)

// MockOIDCClient is a mock of Client interface.
type MockOIDCClient struct {
	ctrl     *gomock.Controller
	recorder *MockOIDCClientMockRecorder
	isgomock struct{}
}

// MockOIDCClientMockRecorder is the mock recorder for MockOIDCClient.
type MockOIDCClientMockRecorder struct {
	mock *MockOIDCClient
}

// NewMockOIDCClient creates a new mock instance.
func NewMockOIDCClient(ctrl *gomock.Controller) *MockOIDCClient {
	mock := &MockOIDCClient{ctrl: ctrl}
	mock.recorder = &MockOIDCClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOIDCClient) EXPECT() *MockOIDCClientMockRecorder {
	return m.recorder
}

// GetAccessTokenEncryptedResponseAlg mocks base method.
func (m *MockOIDCClient) GetAccessTokenEncryptedResponseAlg() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessTokenEncryptedResponseAlg")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAccessTokenEncryptedResponseAlg indicates an expected call of GetAccessTokenEncryptedResponseAlg.
func (mr *MockOIDCClientMockRecorder) GetAccessTokenEncryptedResponseAlg() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessTokenEncryptedResponseAlg", reflect.TypeOf((*MockOIDCClient)(nil).GetAccessTokenEncryptedResponseAlg))
}

// GetAccessTokenEncryptedResponseEnc mocks base method.
func (m *MockOIDCClient) GetAccessTokenEncryptedResponseEnc() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessTokenEncryptedResponseEnc")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAccessTokenEncryptedResponseEnc indicates an expected call of GetAccessTokenEncryptedResponseEnc.
func (mr *MockOIDCClientMockRecorder) GetAccessTokenEncryptedResponseEnc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessTokenEncryptedResponseEnc", reflect.TypeOf((*MockOIDCClient)(nil).GetAccessTokenEncryptedResponseEnc))
}

// GetAccessTokenEncryptedResponseKeyID mocks base method.
func (m *MockOIDCClient) GetAccessTokenEncryptedResponseKeyID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessTokenEncryptedResponseKeyID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAccessTokenEncryptedResponseKeyID indicates an expected call of GetAccessTokenEncryptedResponseKeyID.
func (mr *MockOIDCClientMockRecorder) GetAccessTokenEncryptedResponseKeyID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessTokenEncryptedResponseKeyID", reflect.TypeOf((*MockOIDCClient)(nil).GetAccessTokenEncryptedResponseKeyID))
}

// GetAccessTokenSignedResponseAlg mocks base method.
func (m *MockOIDCClient) GetAccessTokenSignedResponseAlg() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessTokenSignedResponseAlg")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAccessTokenSignedResponseAlg indicates an expected call of GetAccessTokenSignedResponseAlg.
func (mr *MockOIDCClientMockRecorder) GetAccessTokenSignedResponseAlg() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessTokenSignedResponseAlg", reflect.TypeOf((*MockOIDCClient)(nil).GetAccessTokenSignedResponseAlg))
}

// GetAccessTokenSignedResponseKeyID mocks base method.
func (m *MockOIDCClient) GetAccessTokenSignedResponseKeyID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessTokenSignedResponseKeyID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAccessTokenSignedResponseKeyID indicates an expected call of GetAccessTokenSignedResponseKeyID.
func (mr *MockOIDCClientMockRecorder) GetAccessTokenSignedResponseKeyID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessTokenSignedResponseKeyID", reflect.TypeOf((*MockOIDCClient)(nil).GetAccessTokenSignedResponseKeyID))
}

// GetAudience mocks base method.
func (m *MockOIDCClient) GetAudience() oauth2.Arguments {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAudience")
	ret0, _ := ret[0].(oauth2.Arguments)
	return ret0
}

// GetAudience indicates an expected call of GetAudience.
func (mr *MockOIDCClientMockRecorder) GetAudience() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAudience", reflect.TypeOf((*MockOIDCClient)(nil).GetAudience))
}

// GetAuthorizationEncryptedResponseAlg mocks base method.
func (m *MockOIDCClient) GetAuthorizationEncryptedResponseAlg() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationEncryptedResponseAlg")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthorizationEncryptedResponseAlg indicates an expected call of GetAuthorizationEncryptedResponseAlg.
func (mr *MockOIDCClientMockRecorder) GetAuthorizationEncryptedResponseAlg() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationEncryptedResponseAlg", reflect.TypeOf((*MockOIDCClient)(nil).GetAuthorizationEncryptedResponseAlg))
}

// GetAuthorizationEncryptedResponseEnc mocks base method.
func (m *MockOIDCClient) GetAuthorizationEncryptedResponseEnc() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationEncryptedResponseEnc")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthorizationEncryptedResponseEnc indicates an expected call of GetAuthorizationEncryptedResponseEnc.
func (mr *MockOIDCClientMockRecorder) GetAuthorizationEncryptedResponseEnc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationEncryptedResponseEnc", reflect.TypeOf((*MockOIDCClient)(nil).GetAuthorizationEncryptedResponseEnc))
}

// GetAuthorizationEncryptedResponseKeyID mocks base method.
func (m *MockOIDCClient) GetAuthorizationEncryptedResponseKeyID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationEncryptedResponseKeyID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthorizationEncryptedResponseKeyID indicates an expected call of GetAuthorizationEncryptedResponseKeyID.
func (mr *MockOIDCClientMockRecorder) GetAuthorizationEncryptedResponseKeyID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationEncryptedResponseKeyID", reflect.TypeOf((*MockOIDCClient)(nil).GetAuthorizationEncryptedResponseKeyID))
}

// GetAuthorizationPolicy mocks base method.
func (m *MockOIDCClient) GetAuthorizationPolicy() oidc.ClientAuthorizationPolicy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationPolicy")
	ret0, _ := ret[0].(oidc.ClientAuthorizationPolicy)
	return ret0
}

// GetAuthorizationPolicy indicates an expected call of GetAuthorizationPolicy.
func (mr *MockOIDCClientMockRecorder) GetAuthorizationPolicy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationPolicy", reflect.TypeOf((*MockOIDCClient)(nil).GetAuthorizationPolicy))
}

// GetAuthorizationPolicyRequiredLevel mocks base method.
func (m *MockOIDCClient) GetAuthorizationPolicyRequiredLevel(subject authorization.Subject) authorization.Level {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationPolicyRequiredLevel", subject)
	ret0, _ := ret[0].(authorization.Level)
	return ret0
}

// GetAuthorizationPolicyRequiredLevel indicates an expected call of GetAuthorizationPolicyRequiredLevel.
func (mr *MockOIDCClientMockRecorder) GetAuthorizationPolicyRequiredLevel(subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationPolicyRequiredLevel", reflect.TypeOf((*MockOIDCClient)(nil).GetAuthorizationPolicyRequiredLevel), subject)
}

// GetAuthorizationSignedResponseAlg mocks base method.
func (m *MockOIDCClient) GetAuthorizationSignedResponseAlg() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationSignedResponseAlg")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthorizationSignedResponseAlg indicates an expected call of GetAuthorizationSignedResponseAlg.
func (mr *MockOIDCClientMockRecorder) GetAuthorizationSignedResponseAlg() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationSignedResponseAlg", reflect.TypeOf((*MockOIDCClient)(nil).GetAuthorizationSignedResponseAlg))
}

// GetAuthorizationSignedResponseKeyID mocks base method.
func (m *MockOIDCClient) GetAuthorizationSignedResponseKeyID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationSignedResponseKeyID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthorizationSignedResponseKeyID indicates an expected call of GetAuthorizationSignedResponseKeyID.
func (mr *MockOIDCClientMockRecorder) GetAuthorizationSignedResponseKeyID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationSignedResponseKeyID", reflect.TypeOf((*MockOIDCClient)(nil).GetAuthorizationSignedResponseKeyID))
}

// GetClaimsStrategy mocks base method.
func (m *MockOIDCClient) GetClaimsStrategy() oidc.ClaimsStrategy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClaimsStrategy")
	ret0, _ := ret[0].(oidc.ClaimsStrategy)
	return ret0
}

// GetClaimsStrategy indicates an expected call of GetClaimsStrategy.
func (mr *MockOIDCClientMockRecorder) GetClaimsStrategy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClaimsStrategy", reflect.TypeOf((*MockOIDCClient)(nil).GetClaimsStrategy))
}

// GetClientSecret mocks base method.
func (m *MockOIDCClient) GetClientSecret() oauth2.ClientSecret {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientSecret")
	ret0, _ := ret[0].(oauth2.ClientSecret)
	return ret0
}

// GetClientSecret indicates an expected call of GetClientSecret.
func (mr *MockOIDCClientMockRecorder) GetClientSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientSecret", reflect.TypeOf((*MockOIDCClient)(nil).GetClientSecret))
}

// GetClientSecretPlainText mocks base method.
func (m *MockOIDCClient) GetClientSecretPlainText() ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientSecretPlainText")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetClientSecretPlainText indicates an expected call of GetClientSecretPlainText.
func (mr *MockOIDCClientMockRecorder) GetClientSecretPlainText() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientSecretPlainText", reflect.TypeOf((*MockOIDCClient)(nil).GetClientSecretPlainText))
}

// GetConsentPolicy mocks base method.
func (m *MockOIDCClient) GetConsentPolicy() oidc.ClientConsentPolicy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsentPolicy")
	ret0, _ := ret[0].(oidc.ClientConsentPolicy)
	return ret0
}

// GetConsentPolicy indicates an expected call of GetConsentPolicy.
func (mr *MockOIDCClientMockRecorder) GetConsentPolicy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsentPolicy", reflect.TypeOf((*MockOIDCClient)(nil).GetConsentPolicy))
}

// GetConsentResponseBody mocks base method.
func (m *MockOIDCClient) GetConsentResponseBody(session oidc.RequesterFormSession, form url.Values, authTime time.Time, disablePreConf bool) oidc.ConsentGetResponseBody {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsentResponseBody", session, form, authTime, disablePreConf)
	ret0, _ := ret[0].(oidc.ConsentGetResponseBody)
	return ret0
}

// GetConsentResponseBody indicates an expected call of GetConsentResponseBody.
func (mr *MockOIDCClientMockRecorder) GetConsentResponseBody(session, form, authTime, disablePreConf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsentResponseBody", reflect.TypeOf((*MockOIDCClient)(nil).GetConsentResponseBody), session, form, authTime, disablePreConf)
}

// GetEffectiveLifespan mocks base method.
func (m *MockOIDCClient) GetEffectiveLifespan(gt oauth2.GrantType, tt oauth2.TokenType, fallback time.Duration) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEffectiveLifespan", gt, tt, fallback)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetEffectiveLifespan indicates an expected call of GetEffectiveLifespan.
func (mr *MockOIDCClientMockRecorder) GetEffectiveLifespan(gt, tt, fallback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEffectiveLifespan", reflect.TypeOf((*MockOIDCClient)(nil).GetEffectiveLifespan), gt, tt, fallback)
}

// GetEnableJWTProfileOAuthAccessTokens mocks base method.
func (m *MockOIDCClient) GetEnableJWTProfileOAuthAccessTokens() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnableJWTProfileOAuthAccessTokens")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetEnableJWTProfileOAuthAccessTokens indicates an expected call of GetEnableJWTProfileOAuthAccessTokens.
func (mr *MockOIDCClientMockRecorder) GetEnableJWTProfileOAuthAccessTokens() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnableJWTProfileOAuthAccessTokens", reflect.TypeOf((*MockOIDCClient)(nil).GetEnableJWTProfileOAuthAccessTokens))
}

// GetEnforcePKCE mocks base method.
func (m *MockOIDCClient) GetEnforcePKCE() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnforcePKCE")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetEnforcePKCE indicates an expected call of GetEnforcePKCE.
func (mr *MockOIDCClientMockRecorder) GetEnforcePKCE() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnforcePKCE", reflect.TypeOf((*MockOIDCClient)(nil).GetEnforcePKCE))
}

// GetEnforcePKCEChallengeMethod mocks base method.
func (m *MockOIDCClient) GetEnforcePKCEChallengeMethod() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnforcePKCEChallengeMethod")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetEnforcePKCEChallengeMethod indicates an expected call of GetEnforcePKCEChallengeMethod.
func (mr *MockOIDCClientMockRecorder) GetEnforcePKCEChallengeMethod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnforcePKCEChallengeMethod", reflect.TypeOf((*MockOIDCClient)(nil).GetEnforcePKCEChallengeMethod))
}

// GetGrantTypes mocks base method.
func (m *MockOIDCClient) GetGrantTypes() oauth2.Arguments {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGrantTypes")
	ret0, _ := ret[0].(oauth2.Arguments)
	return ret0
}

// GetGrantTypes indicates an expected call of GetGrantTypes.
func (mr *MockOIDCClientMockRecorder) GetGrantTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGrantTypes", reflect.TypeOf((*MockOIDCClient)(nil).GetGrantTypes))
}

// GetID mocks base method.
func (m *MockOIDCClient) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockOIDCClientMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockOIDCClient)(nil).GetID))
}

// GetIDTokenEncryptedResponseAlg mocks base method.
func (m *MockOIDCClient) GetIDTokenEncryptedResponseAlg() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDTokenEncryptedResponseAlg")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIDTokenEncryptedResponseAlg indicates an expected call of GetIDTokenEncryptedResponseAlg.
func (mr *MockOIDCClientMockRecorder) GetIDTokenEncryptedResponseAlg() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDTokenEncryptedResponseAlg", reflect.TypeOf((*MockOIDCClient)(nil).GetIDTokenEncryptedResponseAlg))
}

// GetIDTokenEncryptedResponseEnc mocks base method.
func (m *MockOIDCClient) GetIDTokenEncryptedResponseEnc() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDTokenEncryptedResponseEnc")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIDTokenEncryptedResponseEnc indicates an expected call of GetIDTokenEncryptedResponseEnc.
func (mr *MockOIDCClientMockRecorder) GetIDTokenEncryptedResponseEnc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDTokenEncryptedResponseEnc", reflect.TypeOf((*MockOIDCClient)(nil).GetIDTokenEncryptedResponseEnc))
}

// GetIDTokenEncryptedResponseKeyID mocks base method.
func (m *MockOIDCClient) GetIDTokenEncryptedResponseKeyID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDTokenEncryptedResponseKeyID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIDTokenEncryptedResponseKeyID indicates an expected call of GetIDTokenEncryptedResponseKeyID.
func (mr *MockOIDCClientMockRecorder) GetIDTokenEncryptedResponseKeyID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDTokenEncryptedResponseKeyID", reflect.TypeOf((*MockOIDCClient)(nil).GetIDTokenEncryptedResponseKeyID))
}

// GetIDTokenSignedResponseAlg mocks base method.
func (m *MockOIDCClient) GetIDTokenSignedResponseAlg() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDTokenSignedResponseAlg")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIDTokenSignedResponseAlg indicates an expected call of GetIDTokenSignedResponseAlg.
func (mr *MockOIDCClientMockRecorder) GetIDTokenSignedResponseAlg() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDTokenSignedResponseAlg", reflect.TypeOf((*MockOIDCClient)(nil).GetIDTokenSignedResponseAlg))
}

// GetIDTokenSignedResponseKeyID mocks base method.
func (m *MockOIDCClient) GetIDTokenSignedResponseKeyID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDTokenSignedResponseKeyID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIDTokenSignedResponseKeyID indicates an expected call of GetIDTokenSignedResponseKeyID.
func (mr *MockOIDCClientMockRecorder) GetIDTokenSignedResponseKeyID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDTokenSignedResponseKeyID", reflect.TypeOf((*MockOIDCClient)(nil).GetIDTokenSignedResponseKeyID))
}

// GetIntrospectionEncryptedResponseAlg mocks base method.
func (m *MockOIDCClient) GetIntrospectionEncryptedResponseAlg() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntrospectionEncryptedResponseAlg")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIntrospectionEncryptedResponseAlg indicates an expected call of GetIntrospectionEncryptedResponseAlg.
func (mr *MockOIDCClientMockRecorder) GetIntrospectionEncryptedResponseAlg() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntrospectionEncryptedResponseAlg", reflect.TypeOf((*MockOIDCClient)(nil).GetIntrospectionEncryptedResponseAlg))
}

// GetIntrospectionEncryptedResponseEnc mocks base method.
func (m *MockOIDCClient) GetIntrospectionEncryptedResponseEnc() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntrospectionEncryptedResponseEnc")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIntrospectionEncryptedResponseEnc indicates an expected call of GetIntrospectionEncryptedResponseEnc.
func (mr *MockOIDCClientMockRecorder) GetIntrospectionEncryptedResponseEnc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntrospectionEncryptedResponseEnc", reflect.TypeOf((*MockOIDCClient)(nil).GetIntrospectionEncryptedResponseEnc))
}

// GetIntrospectionEncryptedResponseKeyID mocks base method.
func (m *MockOIDCClient) GetIntrospectionEncryptedResponseKeyID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntrospectionEncryptedResponseKeyID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIntrospectionEncryptedResponseKeyID indicates an expected call of GetIntrospectionEncryptedResponseKeyID.
func (mr *MockOIDCClientMockRecorder) GetIntrospectionEncryptedResponseKeyID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntrospectionEncryptedResponseKeyID", reflect.TypeOf((*MockOIDCClient)(nil).GetIntrospectionEncryptedResponseKeyID))
}

// GetIntrospectionSignedResponseAlg mocks base method.
func (m *MockOIDCClient) GetIntrospectionSignedResponseAlg() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntrospectionSignedResponseAlg")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIntrospectionSignedResponseAlg indicates an expected call of GetIntrospectionSignedResponseAlg.
func (mr *MockOIDCClientMockRecorder) GetIntrospectionSignedResponseAlg() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntrospectionSignedResponseAlg", reflect.TypeOf((*MockOIDCClient)(nil).GetIntrospectionSignedResponseAlg))
}

// GetIntrospectionSignedResponseKeyID mocks base method.
func (m *MockOIDCClient) GetIntrospectionSignedResponseKeyID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntrospectionSignedResponseKeyID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIntrospectionSignedResponseKeyID indicates an expected call of GetIntrospectionSignedResponseKeyID.
func (mr *MockOIDCClientMockRecorder) GetIntrospectionSignedResponseKeyID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntrospectionSignedResponseKeyID", reflect.TypeOf((*MockOIDCClient)(nil).GetIntrospectionSignedResponseKeyID))
}

// GetJSONWebKeys mocks base method.
func (m *MockOIDCClient) GetJSONWebKeys() *jose.JSONWebKeySet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSONWebKeys")
	ret0, _ := ret[0].(*jose.JSONWebKeySet)
	return ret0
}

// GetJSONWebKeys indicates an expected call of GetJSONWebKeys.
func (mr *MockOIDCClientMockRecorder) GetJSONWebKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSONWebKeys", reflect.TypeOf((*MockOIDCClient)(nil).GetJSONWebKeys))
}

// GetJSONWebKeysURI mocks base method.
func (m *MockOIDCClient) GetJSONWebKeysURI() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSONWebKeysURI")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetJSONWebKeysURI indicates an expected call of GetJSONWebKeysURI.
func (mr *MockOIDCClientMockRecorder) GetJSONWebKeysURI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSONWebKeysURI", reflect.TypeOf((*MockOIDCClient)(nil).GetJSONWebKeysURI))
}

// GetName mocks base method.
func (m *MockOIDCClient) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockOIDCClientMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockOIDCClient)(nil).GetName))
}

// GetPKCEChallengeMethod mocks base method.
func (m *MockOIDCClient) GetPKCEChallengeMethod() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPKCEChallengeMethod")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPKCEChallengeMethod indicates an expected call of GetPKCEChallengeMethod.
func (mr *MockOIDCClientMockRecorder) GetPKCEChallengeMethod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPKCEChallengeMethod", reflect.TypeOf((*MockOIDCClient)(nil).GetPKCEChallengeMethod))
}

// GetRedirectURIs mocks base method.
func (m *MockOIDCClient) GetRedirectURIs() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRedirectURIs")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetRedirectURIs indicates an expected call of GetRedirectURIs.
func (mr *MockOIDCClientMockRecorder) GetRedirectURIs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRedirectURIs", reflect.TypeOf((*MockOIDCClient)(nil).GetRedirectURIs))
}

// GetRefreshFlowIgnoreOriginalGrantedScopes mocks base method.
func (m *MockOIDCClient) GetRefreshFlowIgnoreOriginalGrantedScopes(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshFlowIgnoreOriginalGrantedScopes", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetRefreshFlowIgnoreOriginalGrantedScopes indicates an expected call of GetRefreshFlowIgnoreOriginalGrantedScopes.
func (mr *MockOIDCClientMockRecorder) GetRefreshFlowIgnoreOriginalGrantedScopes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshFlowIgnoreOriginalGrantedScopes", reflect.TypeOf((*MockOIDCClient)(nil).GetRefreshFlowIgnoreOriginalGrantedScopes), ctx)
}

// GetRequirePushedAuthorizationRequests mocks base method.
func (m *MockOIDCClient) GetRequirePushedAuthorizationRequests() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequirePushedAuthorizationRequests")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetRequirePushedAuthorizationRequests indicates an expected call of GetRequirePushedAuthorizationRequests.
func (mr *MockOIDCClientMockRecorder) GetRequirePushedAuthorizationRequests() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequirePushedAuthorizationRequests", reflect.TypeOf((*MockOIDCClient)(nil).GetRequirePushedAuthorizationRequests))
}

// GetResponseModes mocks base method.
func (m *MockOIDCClient) GetResponseModes() []oauth2.ResponseModeType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResponseModes")
	ret0, _ := ret[0].([]oauth2.ResponseModeType)
	return ret0
}

// GetResponseModes indicates an expected call of GetResponseModes.
func (mr *MockOIDCClientMockRecorder) GetResponseModes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponseModes", reflect.TypeOf((*MockOIDCClient)(nil).GetResponseModes))
}

// GetResponseTypes mocks base method.
func (m *MockOIDCClient) GetResponseTypes() oauth2.Arguments {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResponseTypes")
	ret0, _ := ret[0].(oauth2.Arguments)
	return ret0
}

// GetResponseTypes indicates an expected call of GetResponseTypes.
func (mr *MockOIDCClientMockRecorder) GetResponseTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponseTypes", reflect.TypeOf((*MockOIDCClient)(nil).GetResponseTypes))
}

// GetScopes mocks base method.
func (m *MockOIDCClient) GetScopes() oauth2.Arguments {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScopes")
	ret0, _ := ret[0].(oauth2.Arguments)
	return ret0
}

// GetScopes indicates an expected call of GetScopes.
func (mr *MockOIDCClientMockRecorder) GetScopes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScopes", reflect.TypeOf((*MockOIDCClient)(nil).GetScopes))
}

// GetSectorIdentifierURI mocks base method.
func (m *MockOIDCClient) GetSectorIdentifierURI() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSectorIdentifierURI")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSectorIdentifierURI indicates an expected call of GetSectorIdentifierURI.
func (mr *MockOIDCClientMockRecorder) GetSectorIdentifierURI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSectorIdentifierURI", reflect.TypeOf((*MockOIDCClient)(nil).GetSectorIdentifierURI))
}

// GetUserinfoEncryptedResponseAlg mocks base method.
func (m *MockOIDCClient) GetUserinfoEncryptedResponseAlg() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserinfoEncryptedResponseAlg")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserinfoEncryptedResponseAlg indicates an expected call of GetUserinfoEncryptedResponseAlg.
func (mr *MockOIDCClientMockRecorder) GetUserinfoEncryptedResponseAlg() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserinfoEncryptedResponseAlg", reflect.TypeOf((*MockOIDCClient)(nil).GetUserinfoEncryptedResponseAlg))
}

// GetUserinfoEncryptedResponseEnc mocks base method.
func (m *MockOIDCClient) GetUserinfoEncryptedResponseEnc() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserinfoEncryptedResponseEnc")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserinfoEncryptedResponseEnc indicates an expected call of GetUserinfoEncryptedResponseEnc.
func (mr *MockOIDCClientMockRecorder) GetUserinfoEncryptedResponseEnc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserinfoEncryptedResponseEnc", reflect.TypeOf((*MockOIDCClient)(nil).GetUserinfoEncryptedResponseEnc))
}

// GetUserinfoEncryptedResponseKeyID mocks base method.
func (m *MockOIDCClient) GetUserinfoEncryptedResponseKeyID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserinfoEncryptedResponseKeyID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserinfoEncryptedResponseKeyID indicates an expected call of GetUserinfoEncryptedResponseKeyID.
func (mr *MockOIDCClientMockRecorder) GetUserinfoEncryptedResponseKeyID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserinfoEncryptedResponseKeyID", reflect.TypeOf((*MockOIDCClient)(nil).GetUserinfoEncryptedResponseKeyID))
}

// GetUserinfoSignedResponseAlg mocks base method.
func (m *MockOIDCClient) GetUserinfoSignedResponseAlg() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserinfoSignedResponseAlg")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserinfoSignedResponseAlg indicates an expected call of GetUserinfoSignedResponseAlg.
func (mr *MockOIDCClientMockRecorder) GetUserinfoSignedResponseAlg() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserinfoSignedResponseAlg", reflect.TypeOf((*MockOIDCClient)(nil).GetUserinfoSignedResponseAlg))
}

// GetUserinfoSignedResponseKeyID mocks base method.
func (m *MockOIDCClient) GetUserinfoSignedResponseKeyID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserinfoSignedResponseKeyID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserinfoSignedResponseKeyID indicates an expected call of GetUserinfoSignedResponseKeyID.
func (mr *MockOIDCClientMockRecorder) GetUserinfoSignedResponseKeyID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserinfoSignedResponseKeyID", reflect.TypeOf((*MockOIDCClient)(nil).GetUserinfoSignedResponseKeyID))
}

// IsAuthenticationLevelSufficient mocks base method.
func (m *MockOIDCClient) IsAuthenticationLevelSufficient(level authentication.Level, subject authorization.Subject) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthenticationLevelSufficient", level, subject)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAuthenticationLevelSufficient indicates an expected call of IsAuthenticationLevelSufficient.
func (mr *MockOIDCClientMockRecorder) IsAuthenticationLevelSufficient(level, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthenticationLevelSufficient", reflect.TypeOf((*MockOIDCClient)(nil).IsAuthenticationLevelSufficient), level, subject)
}

// IsPublic mocks base method.
func (m *MockOIDCClient) IsPublic() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPublic")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPublic indicates an expected call of IsPublic.
func (mr *MockOIDCClientMockRecorder) IsPublic() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPublic", reflect.TypeOf((*MockOIDCClient)(nil).IsPublic))
}

// ValidateResponseModePolicy mocks base method.
func (m *MockOIDCClient) ValidateResponseModePolicy(r oauth2.AuthorizeRequester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateResponseModePolicy", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateResponseModePolicy indicates an expected call of ValidateResponseModePolicy.
func (mr *MockOIDCClientMockRecorder) ValidateResponseModePolicy(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateResponseModePolicy", reflect.TypeOf((*MockOIDCClient)(nil).ValidateResponseModePolicy), r)
}
