// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/authelia/authelia/v4/internal/random (interfaces: Provider)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRandom is a mock of Provider interface.
type MockRandom struct {
	ctrl     *gomock.Controller
	recorder *MockRandomMockRecorder
}

// MockRandomMockRecorder is the mock recorder for MockRandom.
type MockRandomMockRecorder struct {
	mock *MockRandom
}

// NewMockRandom creates a new mock instance.
func NewMockRandom(ctrl *gomock.Controller) *MockRandom {
	mock := &MockRandom{ctrl: ctrl}
	mock.recorder = &MockRandomMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRandom) EXPECT() *MockRandomMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockRandom) Generate() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockRandomMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockRandom)(nil).Generate))
}

// GenerateCustom mocks base method.
func (m *MockRandom) GenerateCustom(arg0 int, arg1 []byte) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCustom", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GenerateCustom indicates an expected call of GenerateCustom.
func (mr *MockRandomMockRecorder) GenerateCustom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCustom", reflect.TypeOf((*MockRandom)(nil).GenerateCustom), arg0, arg1)
}

// GenerateString mocks base method.
func (m *MockRandom) GenerateString(arg0 int, arg1 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateString", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateString indicates an expected call of GenerateString.
func (mr *MockRandomMockRecorder) GenerateString(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateString", reflect.TypeOf((*MockRandom)(nil).GenerateString), arg0, arg1)
}
