---
services:
  duo-api:
    image: 'authelia/integration-duo'
    cpus: 2
    mem_limit: 1g
    volumes:
      - './example/compose/duo-api/duo_api.js:/usr/app/src/duo_api.js'
    networks:
      authelianet: {}
...
