FROM golang:1.24.1-alpine@sha256:43c094ad24b6ac0546c62193baeb3e6e49ce14d3250845d166c77c25f64b0386

ARG USER_ID
ARG GROUP_ID

RUN addgroup --gid ${GROUP_ID} dev && \
    adduser --uid ${USER_ID} -G dev -D dev && \
    apk --no-cache add gcc git musl-dev

RUN \
	mkdir -p /config && chown dev:dev /config

USER dev

ENV PATH="/app:${PATH}" \
	X_AUTHELIA_CONFIG="/config/configuration.yml"

VOLUME /config

EXPOSE 9091
