FROM golang:1.25.2-alpine@sha256:8280f72610be84e514284bc04de455365d698128e0aaea4e12e06c9b320b58ec

ARG USER_ID
ARG GROUP_ID

RUN addgroup --gid ${GROUP_ID} dev && \
    adduser --uid ${USER_ID} -G dev -D dev && \
    apk --no-cache add gcc git musl-dev

RUN \
	mkdir -p /config && chown dev:dev /config

USER dev

ENV PATH="/app:${PATH}" \
	X_AUTHELIA_CONFIG="/config/configuration.yml"

VOLUME /config

EXPOSE 9091
