FROM node:22-alpine@sha256:008735b83ef98c7635b5b73cb9b597172fe1895619a8d65378fa7110e427abb5

ARG USER_ID
ARG GROUP_ID

RUN yarn global add pnpm && \
    deluser node && \
    addgroup --gid ${GROUP_ID} dev && \
    adduser --uid ${USER_ID} -G dev -D dev

USER dev

EXPOSE 3000
