FROM node:25-alpine@sha256:08e94d88b58859f44d89e0597b416385840e69a1ec56c800c810dfb8c8d0c1bf

ARG USER_ID
ARG GROUP_ID

RUN yarn global add pnpm && \
    deluser node && \
    addgroup --gid ${GROUP_ID} dev && \
    adduser --uid ${USER_ID} -G dev -D dev

USER dev

EXPOSE 3000
