FROM golang:1.25.0-alpine@sha256:77dd832edf2752dafd030693bef196abb24dcba3a2bc3d7a6227a7a1dae73169

ARG USER_ID
ARG GROUP_ID

RUN addgroup --gid ${GROUP_ID} dev && \
    adduser --uid ${USER_ID} -G dev -D dev && \
    apk --no-cache add gcc git musl-dev

RUN \
	mkdir -p /config && chown dev:dev /config

USER dev

ENV PATH="/app:${PATH}" \
	X_AUTHELIA_CONFIG="/config/configuration.yml"

VOLUME /config

EXPOSE 9091
