FROM node:22-alpine

ARG USER_ID
ARG GROUP_ID

RUN yarn global add pnpm && \
    deluser node && \
    addgroup --gid ${GROUP_ID} dev && \
    adduser --uid ${USER_ID} -G dev -D dev

USER dev

EXPOSE 3000
