---
services:
  authelia-frontend:
    image: nginx:alpine
    volumes:
      - './example/compose/authelia/resources/nginx.conf:/etc/nginx/nginx.conf'
    labels:
      # Traefik 1.x
      - 'traefik.frontend.rule=Host:login.example.com'
      # Traefik 2.x / 3.x
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia_frontend.rule=Host(`login.example.com`) || Host(`login.example.com`) && PathPrefix(`${PathPrefix}/`)'  # yamllint disable-line rule:line-length
      - 'traefik.http.routers.authelia_frontend.entrypoints=https'
      - 'traefik.http.routers.authelia_frontend.tls=true'
      - 'traefik.http.services.authelia_frontend.loadbalancer.server.port=3000'
    networks:
      - authelianet
    expose:
      - 3000
...
