---
services:
  traefik:
    cpus: 2
    mem_limit: 1g
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './example/compose/traefik/config:/config'
      - './common/pki:/pki'
      - '${SUITE_TMP:-/tmp}:/tmp'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.api.rule: 'Host(`traefik.example.com`)'
      traefik.http.routers.api.entrypoints: 'https'
      traefik.http.routers.api.service: 'api@internal'
      traefik.http.routers.api.tls: 'true'
      traefik.http.middlewares.authelia.forwardAuth.address: 'https://authelia-backend:9091${PathPrefix:-}/api/authz/forward-auth'  # yamllint disable-line rule:line-length
      traefik.http.middlewares.authelia.forwardAuth.tls.insecureSkipVerify: 'true'
      traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader: 'true'
      traefik.http.middlewares.authelia.forwardAuth.maxResponseBodySize: '8192'
      traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders: 'Authorization,Proxy-Authorization,Remote-User,Remote-Groups,Remote-Email,Remote-Name'  # yamllint disable-line rule:line-length
    command:
      - '--accesslog=true'
      - '--accesslog.filepath=/tmp/traefik-access-${COMPOSE_PROJECT_NAME:-authelia}.log'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--entrypoints.https.address=:8080/tcp'
      - '--global.checknewversion=false'
      - '--global.sendanonymoususage=false'
      - '--log.level=DEBUG'
      - '--providers.docker.constraints=Label(`com.docker.compose.project`,`${COMPOSE_PROJECT_NAME:-authelia}`)'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=${COMPOSE_PROJECT_NAME:-authelia}_authelianet'
      - '--providers.file.directory=/config/dynamic/'
      - '--providers.file.watch=true'
      - '--providers.providersthrottleduration=5s'
      - '--serverstransport.insecureskipverify=true'
    networks:
      authelianet:
        aliases:
          - login.example.com
        ipv4_address: ${SUITE_SUBNET:-192.168.240}.100
...
