---
services:
  traefik:
    image: traefik:v1.7.34-alpine
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      - 'traefik.frontend.rule=Host:traefik.example.com'
      - 'traefik.port=8081'
    command:
      - '--api'
      - '--api.entrypoint=api'
      - '--docker'
      - '--defaultentrypoints=https'
      - '--logLevel=DEBUG'
      - '--traefiklog=true'
      - '--traefiklog.filepath=/var/log/traefik.log'
      - '--entryPoints=Name:https Address::8080 TLS'
      - '--entryPoints=Name:api Address::8081'
      - '--insecureSkipVerify=true'
    networks:
      authelianet:
        ipv4_address: 192.168.240.100
...
