#!/bin/sh

# SPDX-FileCopyrightText: 2019 Authelia
#
# SPDX-License-Identifier: Apache-2.0

if [ -n "$NO_HOOK" ]; then
  exit 0
fi

. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/required-apps"

golangci-lint run -v --fix && \
cd web && ${PMGR_RUN} lint
