#!/bin/sh

if [ ! -x "$(command -v golangci-lint)" ]; then
  echo "You must install golangci-lint."
  exit 1
fi

if [ -x "$(command -v pnpm)" ]; then
  export PMGR_RUN="pnpm"
  export PMGR_EXEC="pnpm"
elif [ -x "$(command -v yarn)" ]; then
  export PMGR_RUN="yarn run"
  export PMGR_EXEC="yarn dlx"
elif [ -x "$(command -v npm)" ]; then
  export PMGR_RUN="npm run"
  export PMGR_EXEC="npx"
else
	echo "You must install a node package manager (pnpm, yarn, or npm)."
	exit 1
fi
