{
 "title": "Single Sign-On",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(authelia_request,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": " Requests",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(authelia_request{instance=~\"$instance\",code=~\"30.*\"})",
     "legendFormat": "Redirect"
    },
    {
     "expr": "sum(authelia_request{instance=~\"$instance\",code=~\"40.*\"})",
     "legendFormat": "Unauthorized"
    }
   ]
  },
  {
   "title": " Factor",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(authelia_authentication_first_factor{instance=~\"$instance\",success=\"true\"}) + sum(authelia_authentication_second_factor{instance=~\"$instance\",success=\"true\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(authelia_authentication_first_factor{instance=~\"$instance\",success=\"false\"}) + sum(authelia_authentication_second_factor{instance=~\"$instance\",success=\"false\"})",
     "legendFormat": "Fail"
    }
   ]
  },
  {
   "title": " Factor fail",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(authelia_authentication_first_factor{instance=~\"$instance\",success=\"false\"})",
     "legendFormat": "1º Fail"
    },
    {
     "expr": "sum(authelia_authentication_second_factor{instance=~\"$instance\",success=\"false\"})",
     "legendFormat": "2º Fail"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(authelia_request{instance=~\"$instance\",code=~\"20.*\"})"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(authelia_request{instance=~\"$instance\",code=~\"20.*\"})"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ceil(rate(authelia_request{instance=~\"$instance\",code=~\"30.*\"}[$__rate_interval])))",
     "legendFormat": "Redirect"
    },
    {
     "expr": "sum(ceil(rate(authelia_request{instance=~\"$instance\",code=~\"40.*\"}[$__rate_interval])))",
     "legendFormat": "Unauthorized"
    },
    {
     "expr": "sum(ceil(irate(authelia_request{instance=~\"$instance\",code=~\"20.*\"}[$__rate_interval])))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Authentication",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ceil(rate(authelia_authentication_first_factor{instance=~\"$instance\",success=\"true\"}[$__rate_interval])))",
     "legendFormat": "First factor success"
    },
    {
     "expr": "sum(ceil(rate(authelia_authentication_first_factor{instance=~\"$instance\",success=\"false\"}[$__rate_interval])))",
     "legendFormat": "First factor fail"
    },
    {
     "expr": "sum(ceil(rate(authelia_authentication_second_factor{instance=~\"$instance\",success=\"true\"}[$__rate_interval])))",
     "legendFormat": "Second factor success"
    },
    {
     "expr": "sum(ceil(rate(authelia_authentication_second_factor{instance=~\"$instance\",success=\"false\"}[$__rate_interval])))",
     "legendFormat": "Second factor fail"
    }
   ]
  },
  {
   "title": "Requests not verified",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ceil(irate(authelia_request{instance=~\"$instance\",code=~\"20.*\"}[$__rate_interval]))) - sum(ceil(irate(authelia_verify_request{instance=~\"$instance\",code=~\"20.*\"}[$__rate_interval])))",
     "legendFormat": "Success not verified"
    },
    {
     "expr": "sum(ceil(rate(authelia_request{instance=~\"$instance\",code=~\"40.*\"}[$__rate_interval]))) - sum(ceil(rate(authelia_verify_request{instance=~\"$instance\",code=~\"40.*\"}[$__rate_interval])))",
     "legendFormat": "Unauthorized not verified"
    }
   ]
  }
 ]
}