package schema

import "time"

type Cache struct {
	Redis         *RedisCache         `koanf:"redis" yaml:"redis,omitempty" toml:"redis,omitempty" json:"redis,omitempty" jsonschema:"title=Redis Cache" jsonschema_description:"Redis Cache Configuration."`
	RedisSentinel *RedisSentinelCache `koanf:"redis_sentinel" yaml:"redis_sentinel,omitempty" toml:"redis_sentinel,omitempty" json:"redis_sentinel,omitempty" jsonschema:"title=Redis Sentinel Cache" jsonschema_description:"Redis Sentinel Cache Configuration."`
	RedisCluster  *RedisClusterCache  `koanf:"redis_cluster" yaml:"redis_cluster,omitempty" toml:"redis_cluster,omitempty" json:"redis_cluster,omitempty" jsonschema:"title=Redis Cluster Cache" jsonschema_description:"Redis Cluster Cache Configuration."`
}

type RedisCache struct {
	Address                    *AddressTCP   `koanf:"address" yaml:"address,omitempty" toml:"address,omitempty" json:"address,omitempty" jsonschema:"title=Address" jsonschema_description:"The address for the Redis server to connect to."`
	Database                   int           `koanf:"database" yaml:"database,omitempty" toml:"database,omitempty" json:"database,omitempty" jsonschema:"title=Database" jsonschema_description:"The database to use for the Redis server."`
	Username                   string        `koanf:"username" yaml:"username,omitempty" toml:"username,omitempty" json:"username,omitempty" jsonschema:"title=Username" jsonschema_description:"The username to use for the Redis server."`
	Password                   string        `koanf:"password" yaml:"password,omitempty" toml:"password,omitempty" json:"password,omitempty" jsonschema:"title=Password" jsonschema_description:"The password to use for the Redis server."`
	TLS                        *TLS          `koanf:"tls" yaml:"tls,omitempty" toml:"tls,omitempty" json:"tls,omitempty" jsonschema:"title=TLS" jsonschema_description:"The TLS configuration for the Redis server."`
	DialTimeout                time.Duration `koanf:"dial_timeout" yaml:"dial_timeout,omitempty" toml:"dial_timeout,omitempty" json:"dial_timeout,omitempty" jsonschema:"default=10 seconds,title=Dial Timeout" jsonschema_description:"The dial timeout for the Redis server."`
	ReadTimeout                time.Duration `koanf:"read_timeout" yaml:"read_timeout,omitempty" toml:"read_timeout,omitempty" json:"read_timeout,omitempty" jsonschema:"default=10 seconds,title=Read Timeout" jsonschema_description:"The read timeout for the Redis server."`
	WriteTimeout               time.Duration `koanf:"write_timeout" yaml:"write_timeout,omitempty" toml:"write_timeout,omitempty" json:"write_timeout,omitempty" jsonschema:"default=10 seconds,title=Write Timeout" jsonschema_description:"The write timeout for the Redis server."`
	ConnectionTimeout          time.Duration `koanf:"connection_timeout" yaml:"connection_timeout,omitempty" toml:"connection_timeout,omitempty" json:"connection_timeout,omitempty" jsonschema:"default=10 seconds,title=Connection Timeout" jsonschema_description:"The connection timeout for the Redis server."`
	IdleTimeout                time.Duration `koanf:"idle_timeout" yaml:"idle_timeout,omitempty" toml:"idle_timeout,omitempty" json:"idle_timeout,omitempty" jsonschema:"default=10 seconds,title=Idle Timeout" jsonschema_description:"The connection idle timeout for the Redis server."`
	PoolTimeout                time.Duration `koanf:"pool_timeout" yaml:"pool_timeout,omitempty" toml:"pool_timeout,omitempty" json:"pool_timeout,omitempty" jsonschema:"default=10 seconds,title=Pool Timeout" jsonschema_description:"The pool timeout for the Redis server."`
	MinimumRetryBackoff        time.Duration `koanf:"minimum_retry_backoff" yaml:"minimum_retry_backoff,omitempty" toml:"minimum_retry_backoff,omitempty" json:"minimum_retry_backoff,omitempty" jsonschema:"default=100 milliseconds,title=Minimum Retry Backoff" jsonschema_description:"The minimum retry backoff to use when connecting to the Redis server."`
	MaximumRetryBackoff        time.Duration `koanf:"maximum_retry_backoff" yaml:"maximum_retry_backoff,omitempty" toml:"maximum_retry_backoff,omitempty" json:"maximum_retry_backoff,omitempty" jsonschema:"default=100 milliseconds,title=Maximum Retry Backoff" jsonschema_description:"The maximum retry backoff to use when connecting to the Redis server."`
	MaximumRetries             int           `koanf:"maximum_retries" yaml:"maximum_retries,omitempty" toml:"maximum_retries,omitempty" json:"maximum_retries,omitempty" jsonschema:"default=3,title=Max Retries" jsonschema_description:"The maximum number of retries to attempt when connecting to the Redis server."`
	PoolSize                   int           `koanf:"pool_size" yaml:"pool_size,omitempty" toml:"pool_size,omitempty" json:"pool_size,omitempty" jsonschema:"default=10,title=Pool Size" jsonschema_description:"The pool size to use when connecting to the Redis server."`
	PoolMinimumIdleConnections int           `koanf:"pool_minimum_idle_connections" yaml:"pool_minimum_idle_connections,omitempty" toml:"pool_minimum_idle_connections,omitempty" json:"pool_minimum_idle_connections,omitempty" jsonschema:"default=10,title=Pool Minimum Idle Connections" jsonschema_description:"The minimum idle connections to keep open with the pool when connecting to the Redis server."`
	PoolMaximumIdleConnections int           `koanf:"pool_maximum_idle_connections" yaml:"pool_maximum_idle_connections,omitempty" toml:"pool_maximum_idle_connections,omitempty" json:"pool_maximum_idle_connections,omitempty" jsonschema:"default=10,title=Pool Maximum Idle Connections" jsonschema_description:"The maximum idle connections to keep open with the pool when connecting to the Redis server."`
	PoolMaximumConnections     int           `koanf:"pool_maximum_connections" yaml:"pool_maximum_connections,omitempty" toml:"pool_maximum_connections,omitempty" json:"pool_maximum_connections,omitempty" jsonschema:"default=10,title=Pool Maximum Connections" jsonschema_description:"The maximum number of connections the pool can have open when connecting to the Redis server."`
}

type RedisSentinelCache struct {
	MasterName                 string
	SentinelUsername           string
	SentinelPassword           string
	Addresses                  []*AddressTCP `koanf:"address" yaml:"address,omitempty" toml:"address,omitempty" json:"address,omitempty" jsonschema:"title=Address" jsonschema_description:"The address for the Redis server to connect to."`
	RouteByReplica             bool
	RouteByLatency             bool
	RouteRandomly              bool
	Database                   int           `koanf:"database" yaml:"database,omitempty" toml:"database,omitempty" json:"database,omitempty" jsonschema:"title=Database" jsonschema_description:"The database to use for the Redis server."`
	Username                   string        `koanf:"username" yaml:"username,omitempty" toml:"username,omitempty" json:"username,omitempty" jsonschema:"title=Username" jsonschema_description:"The username to use for the Redis server."`
	Password                   string        `koanf:"password" yaml:"password,omitempty" toml:"password,omitempty" json:"password,omitempty" jsonschema:"title=Password" jsonschema_description:"The password to use for the Redis server."`
	TLS                        *TLS          `koanf:"tls" yaml:"tls,omitempty" toml:"tls,omitempty" json:"tls,omitempty" jsonschema:"title=TLS" jsonschema_description:"The TLS configuration for the Redis server."`
	DialTimeout                time.Duration `koanf:"dial_timeout" yaml:"dial_timeout,omitempty" toml:"dial_timeout,omitempty" json:"dial_timeout,omitempty" jsonschema:"default=10 seconds,title=Dial Timeout" jsonschema_description:"The dial timeout for the Redis server."`
	ReadTimeout                time.Duration `koanf:"read_timeout" yaml:"read_timeout,omitempty" toml:"read_timeout,omitempty" json:"read_timeout,omitempty" jsonschema:"default=10 seconds,title=Read Timeout" jsonschema_description:"The read timeout for the Redis server."`
	WriteTimeout               time.Duration `koanf:"write_timeout" yaml:"write_timeout,omitempty" toml:"write_timeout,omitempty" json:"write_timeout,omitempty" jsonschema:"default=10 seconds,title=Write Timeout" jsonschema_description:"The write timeout for the Redis server."`
	ConnectionTimeout          time.Duration `koanf:"connection_timeout" yaml:"connection_timeout,omitempty" toml:"connection_timeout,omitempty" json:"connection_timeout,omitempty" jsonschema:"default=10 seconds,title=Connection Timeout" jsonschema_description:"The connection timeout for the Redis server."`
	IdleTimeout                time.Duration `koanf:"idle_timeout" yaml:"idle_timeout,omitempty" toml:"idle_timeout,omitempty" json:"idle_timeout,omitempty" jsonschema:"default=10 seconds,title=Idle Timeout" jsonschema_description:"The connection idle timeout for the Redis server."`
	PoolTimeout                time.Duration `koanf:"pool_timeout" yaml:"pool_timeout,omitempty" toml:"pool_timeout,omitempty" json:"pool_timeout,omitempty" jsonschema:"default=10 seconds,title=Pool Timeout" jsonschema_description:"The pool timeout for the Redis server."`
	MinimumRetryBackoff        time.Duration `koanf:"minimum_retry_backoff" yaml:"minimum_retry_backoff,omitempty" toml:"minimum_retry_backoff,omitempty" json:"minimum_retry_backoff,omitempty" jsonschema:"default=100 milliseconds,title=Minimum Retry Backoff" jsonschema_description:"The minimum retry backoff to use when connecting to the Redis server."`
	MaximumRetryBackoff        time.Duration `koanf:"maximum_retry_backoff" yaml:"maximum_retry_backoff,omitempty" toml:"maximum_retry_backoff,omitempty" json:"maximum_retry_backoff,omitempty" jsonschema:"default=100 milliseconds,title=Maximum Retry Backoff" jsonschema_description:"The maximum retry backoff to use when connecting to the Redis server."`
	MaximumRetries             int           `koanf:"maximum_retries" yaml:"maximum_retries,omitempty" toml:"maximum_retries,omitempty" json:"maximum_retries,omitempty" jsonschema:"default=3,title=Max Retries" jsonschema_description:"The maximum number of retries to attempt when connecting to the Redis server."`
	PoolSize                   int           `koanf:"pool_size" yaml:"pool_size,omitempty" toml:"pool_size,omitempty" json:"pool_size,omitempty" jsonschema:"default=10,title=Pool Size" jsonschema_description:"The pool size to use when connecting to the Redis server."`
	PoolMinimumIdleConnections int           `koanf:"pool_minimum_idle_connections" yaml:"pool_minimum_idle_connections,omitempty" toml:"pool_minimum_idle_connections,omitempty" json:"pool_minimum_idle_connections,omitempty" jsonschema:"default=10,title=Pool Minimum Idle Connections" jsonschema_description:"The minimum idle connections to keep open with the pool when connecting to the Redis server."`
	PoolMaximumIdleConnections int           `koanf:"pool_maximum_idle_connections" yaml:"pool_maximum_idle_connections,omitempty" toml:"pool_maximum_idle_connections,omitempty" json:"pool_maximum_idle_connections,omitempty" jsonschema:"default=10,title=Pool Maximum Idle Connections" jsonschema_description:"The maximum idle connections to keep open with the pool when connecting to the Redis server."`
	PoolMaximumConnections     int           `koanf:"pool_maximum_connections" yaml:"pool_maximum_connections,omitempty" toml:"pool_maximum_connections,omitempty" json:"pool_maximum_connections,omitempty" jsonschema:"default=10,title=Pool Maximum Connections" jsonschema_description:"The maximum number of connections the pool can have open when connecting to the Redis server."`
}

type RedisClusterCache struct {
	Addresses                  []*AddressTCP `koanf:"address" yaml:"address,omitempty" toml:"address,omitempty" json:"address,omitempty" jsonschema:"title=Address" jsonschema_description:"The address for the Redis server to connect to."`
	RouteByReplica             bool
	RouteByLatency             bool
	RouteRandomly              bool
	Username                   string        `koanf:"username" yaml:"username,omitempty" toml:"username,omitempty" json:"username,omitempty" jsonschema:"title=Username" jsonschema_description:"The username to use for the Redis server."`
	Password                   string        `koanf:"password" yaml:"password,omitempty" toml:"password,omitempty" json:"password,omitempty" jsonschema:"title=Password" jsonschema_description:"The password to use for the Redis server."`
	TLS                        *TLS          `koanf:"tls" yaml:"tls,omitempty" toml:"tls,omitempty" json:"tls,omitempty" jsonschema:"title=TLS" jsonschema_description:"The TLS configuration for the Redis server."`
	DialTimeout                time.Duration `koanf:"dial_timeout" yaml:"dial_timeout,omitempty" toml:"dial_timeout,omitempty" json:"dial_timeout,omitempty" jsonschema:"default=10 seconds,title=Dial Timeout" jsonschema_description:"The dial timeout for the Redis server."`
	ReadTimeout                time.Duration `koanf:"read_timeout" yaml:"read_timeout,omitempty" toml:"read_timeout,omitempty" json:"read_timeout,omitempty" jsonschema:"default=10 seconds,title=Read Timeout" jsonschema_description:"The read timeout for the Redis server."`
	WriteTimeout               time.Duration `koanf:"write_timeout" yaml:"write_timeout,omitempty" toml:"write_timeout,omitempty" json:"write_timeout,omitempty" jsonschema:"default=10 seconds,title=Write Timeout" jsonschema_description:"The write timeout for the Redis server."`
	ConnectionTimeout          time.Duration `koanf:"connection_timeout" yaml:"connection_timeout,omitempty" toml:"connection_timeout,omitempty" json:"connection_timeout,omitempty" jsonschema:"default=10 seconds,title=Connection Timeout" jsonschema_description:"The connection timeout for the Redis server."`
	IdleTimeout                time.Duration `koanf:"idle_timeout" yaml:"idle_timeout,omitempty" toml:"idle_timeout,omitempty" json:"idle_timeout,omitempty" jsonschema:"default=10 seconds,title=Idle Timeout" jsonschema_description:"The connection idle timeout for the Redis server."`
	PoolTimeout                time.Duration `koanf:"pool_timeout" yaml:"pool_timeout,omitempty" toml:"pool_timeout,omitempty" json:"pool_timeout,omitempty" jsonschema:"default=10 seconds,title=Pool Timeout" jsonschema_description:"The pool timeout for the Redis server."`
	MinimumRetryBackoff        time.Duration `koanf:"minimum_retry_backoff" yaml:"minimum_retry_backoff,omitempty" toml:"minimum_retry_backoff,omitempty" json:"minimum_retry_backoff,omitempty" jsonschema:"default=100 milliseconds,title=Minimum Retry Backoff" jsonschema_description:"The minimum retry backoff to use when connecting to the Redis server."`
	MaximumRetryBackoff        time.Duration `koanf:"maximum_retry_backoff" yaml:"maximum_retry_backoff,omitempty" toml:"maximum_retry_backoff,omitempty" json:"maximum_retry_backoff,omitempty" jsonschema:"default=100 milliseconds,title=Maximum Retry Backoff" jsonschema_description:"The maximum retry backoff to use when connecting to the Redis server."`
	MaximumRedirects           int           `koanf:"maximum_redirects" yaml:"maximum_redirects,omitempty" toml:"maximum_redirects,omitempty" json:"maximum_redirects,omitempty" jsonschema:"default=3,title=Max Retries" jsonschema_description:"The maximum number of redirects to follow when connecting to the Redis server."`
	PoolSize                   int           `koanf:"pool_size" yaml:"pool_size,omitempty" toml:"pool_size,omitempty" json:"pool_size,omitempty" jsonschema:"default=10,title=Pool Size" jsonschema_description:"The pool size to use when connecting to the Redis server."`
	PoolMinimumIdleConnections int           `koanf:"pool_minimum_idle_connections" yaml:"pool_minimum_idle_connections,omitempty" toml:"pool_minimum_idle_connections,omitempty" json:"pool_minimum_idle_connections,omitempty" jsonschema:"default=10,title=Pool Minimum Idle Connections" jsonschema_description:"The minimum idle connections to keep open with the pool when connecting to the Redis server."`
	PoolMaximumIdleConnections int           `koanf:"pool_maximum_idle_connections" yaml:"pool_maximum_idle_connections,omitempty" toml:"pool_maximum_idle_connections,omitempty" json:"pool_maximum_idle_connections,omitempty" jsonschema:"default=10,title=Pool Maximum Idle Connections" jsonschema_description:"The maximum idle connections to keep open with the pool when connecting to the Redis server."`
	PoolMaximumConnections     int           `koanf:"pool_maximum_connections" yaml:"pool_maximum_connections,omitempty" toml:"pool_maximum_connections,omitempty" json:"pool_maximum_connections,omitempty" jsonschema:"default=10,title=Pool Maximum Connections" jsonschema_description:"The maximum number of connections the pool can have open when connecting to the Redis server."`
}
