---
# yaml-language-server: $schema=https://json.schemastore.org/codecov.json
codecov:
  require_ci_to_pass: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

coverage:
  precision: 2
  round: down
  range: "70...95"
  status:
    project:
      default: false
      backend:
        target: auto
        threshold: 0.15%
        flags:
          - backend
      frontend:
        target: auto
        threshold: 0.15%
        flags:
          - frontend
    patch:
      default:
        target: 90%
        threshold: 10%

fixes:
  - "src/::web/src/"

flags:
  backend:
    paths:
      - "cmd/authelia/"
      - "internal/"
      - "!internal/mocks/"
      - "!internal/suites/"
      - "!internal/**/*_mock_test.go"
  frontend:
    paths:
      - "web/"
      - "!web/coverage/"

ignore:
  - "**/coverage.txt"
...
