---
ignore:
  - vulnerability: CVE-2024-58251
    package:
      name: busybox
      version: 1.37.0
      type: binary
  - vulnerability: CVE-2025-46394
    package:
      name: busybox
      version: 1.37.0
      type: binary
  - vulnerability: CVE-2025-61727
    package:
      name: stdlib
      version: go1.25.4
      type: go-module
  - vulnerability: CVE-2025-61729
    package:
      name: stdlib
      version: go1.25.4
      type: go-module
...
