---
pre-commit:
  piped: true
  jobs:
    - name: check tools
      # yamllint disable rule:indentation
      run: |
        MISSING=()

        for TOOL in gitleaks golangci-lint pnpm yamllint; do
          if ! command -v ${TOOL} > /dev/null 2>&1; then
          MISSING+=("${TOOL}")
          fi
        done

        if [ ${#MISSING[@]} -gt 0 ]; then
          COUNT=${#MISSING[@]}
          if [ $COUNT -eq 1 ]; then
            LIST="${MISSING[0]}"
          elif [ $COUNT -eq 2 ]; then
            LIST="${MISSING[0]} and ${MISSING[1]}"
          else
            LIST="$(IFS=, ; echo "${MISSING[*]:0:$COUNT-1}" | sed 's/,/, /g') and ${MISSING[$COUNT-1]}"
          fi

          echo "❌ You must install ${LIST}"
          exit 1
        fi
      # yamllint enable rule:indentation

    - name: linters
      group:
        parallel: true
        jobs:
          - name: eslint
            run: pnpm lint
            root: "web/"
            glob: "*.{js,jsx,ts,tsx}"
            stage_fixed: true

          - name: gitleaks
            run: gitleaks detect --no-banner --no-color -b .gitleaks-baseline.json

          - name: golangci-lint
            run: golangci-lint run --fix
            glob: "*.go"
            stage_fixed: true

          - name: yamllint
            run: yamllint -f parsable .
            glob: "*.{yml,yaml}"

commit-msg:
  jobs:
    - name: commitlint
      run: pnpm commitlint --edit
      root: "web/"
...
