# SPDX-FileCopyrightText: 2026 Authelia
#
# SPDX-License-Identifier: Apache-2.0

#Type   Name       ID      GECOS                     Home directory  Shell
u!      authelia   -       "Authelia Daemon User"    /nonexistent
