#Type Path                                    Mode User       Group      Age         Argument
d     /etc/authelia                           0750 root       authelia   -           -
Z     /etc/authelia                          ~0750 root       authelia   -           -
