# ========================================
# ===== Build image for the frontend =====
# ========================================
FROM node:25-alpine@sha256:5209bcaca9836eb3448b650396213dbe9d9a34d31840c2ae1f206cb2986a8543 AS builder-frontend

WORKDIR /node/src/app

COPY --link web ./

# Install the dependencies and build
RUN \
	yarn global add pnpm && \
	pnpm install --frozen-lockfile --ignore-scripts && \
	pnpm coverage

# =======================================
# ===== Build image for the backend =====
# =======================================
FROM golang:1.26.1-bookworm@sha256:a83c153005aa7193aaa915039dba5500ea603360b816f36cdf2df6ebf1ebe2f1 AS builder-backend

WORKDIR /go/src/app

COPY --link go.mod go.sum ./

RUN \
	echo ">> Downloading go modules..." && \
	go mod download

COPY --link / ./

# Prepare static files to be embedded in Go binary
COPY --link --from=builder-frontend /node/src/internal/server/public_html internal/server/public_html

ARG LDFLAGS_EXTRA

RUN \
	mv api internal/server/public_html/api && \
	echo ">> Starting go build..." && \
	CGO_ENABLED=1 CGO_CPPFLAGS="-D_FORTIFY_SOURCE=2 -fstack-protector-strong" CGO_LDFLAGS="-Wl,-z,relro,-z,now" go build \
	-tags dev -ldflags "-linkmode=external -s -w ${LDFLAGS_EXTRA}" -trimpath -buildmode=pie -o authelia ./cmd/authelia

# ===================================
# ===== Authelia official image =====
# ===================================
FROM authelia/base:latest@sha256:3a70f9b3327eb2362902fc2975d290597b161918377dba955e7473bfea526650

WORKDIR /app

ENV \
	PATH="/app:${PATH}" \
	PUID=0 \
	PGID=0 \
	X_AUTHELIA_CONFIG="/config/configuration.yml"

COPY --link --from=builder-backend /go/src/app/authelia /go/src/app/LICENSE /go/src/app/entrypoint.sh /go/src/app/healthcheck.sh ./

COPY --link	--from=builder-backend --chmod=666 /go/src/app/.healthcheck.env ./

EXPOSE 9091

ENTRYPOINT ["/app/entrypoint.sh"]
HEALTHCHECK --interval=30s --timeout=3s --start-period=1m CMD /app/healthcheck.sh
