FROM node:8.7.0-alpine

WORKDIR /usr/app

ADD package.json package.json

RUN apk --update add --no-cache --virtual \
      .build-deps make g++ python && \
      npm install && \
      apk del .build-deps

EXPOSE 8080

VOLUME /usr/app/src
VOLUME /etc/authelia
VOLUME /var/lib/authelia

CMD ["./node_modules/.bin/nodemon", "-e", "yml,js,ts,json", "--exec", "./scripts/run-dev-server.sh"]
