# ========================================
# ===== Build image for the frontend =====
# ========================================
FROM node:24-alpine@sha256:be4d5e92ac68483ec71440bf5934865b4b7fcb93588f17a24d411d15f0204e4f AS builder-frontend

WORKDIR /node/src/app

COPY --link web ./

# Install the dependencies and build
RUN \
	yarn global add pnpm && \
	pnpm install --frozen-lockfile && \
	pnpm coverage

# =======================================
# ===== Build image for the backend =====
# =======================================
FROM golang:1.25.0-bookworm@sha256:81dc45d05a7444ead8c92a389621fafabc8e40f8fd1a19d7e5df14e61e98bc1a AS builder-backend

WORKDIR /go/src/app

COPY --link go.mod go.sum ./

RUN \
	echo ">> Downloading go modules..." && \
	go mod download

COPY --link / ./

# Prepare static files to be embedded in Go binary
COPY --link --from=builder-frontend /node/src/internal/server/public_html internal/server/public_html

ARG LDFLAGS_EXTRA

RUN \
	mv api internal/server/public_html/api && \
	echo ">> Starting go build..." && \
	GOEXPERIMENT="nosynchashtriemap" CGO_ENABLED=1 CGO_CPPFLAGS="-D_FORTIFY_SOURCE=2 -fstack-protector-strong" CGO_LDFLAGS="-Wl,-z,relro,-z,now" go build \
	-tags dev -ldflags "-linkmode=external -s -w ${LDFLAGS_EXTRA}" -trimpath -buildmode=pie -o authelia ./cmd/authelia

# ===================================
# ===== Authelia official image =====
# ===================================
FROM authelia/base:latest

WORKDIR /app

ENV \
	PATH="/app:${PATH}" \
	PUID=0 \
	PGID=0 \
	X_AUTHELIA_CONFIG="/config/configuration.yml"

COPY --link --from=builder-backend /go/src/app/authelia /go/src/app/LICENSE /go/src/app/entrypoint.sh /go/src/app/healthcheck.sh ./

COPY --link	--from=builder-backend --chmod=666 /go/src/app/.healthcheck.env ./

EXPOSE 9091

ENTRYPOINT ["/app/entrypoint.sh"]
HEALTHCHECK --interval=30s --timeout=3s --start-period=1m CMD /app/healthcheck.sh
