version = 1

SPDX-PackageName = "Authelia"
SPDX-PackageSupplier = "Authelia <team@authelia.com>"
SPDX-PackageDownloadLocation = "https://github.com/authelia/authelia"

[[annotations]]
path = "**"
precedence = "closest"

[[annotations]]
path = [
	".all-contributorsrc",
	".buildkite/annotations/bypass",
	".buildkite/annotations/draft",
	".buildkite/annotations/merge-queue",
	".renovaterc",
	"CITATION.cff",
	"cmd/authelia-gen/templates/dot_commitlintrc.cjs.tmpl",
	"cmd/dev/**",
	"docs/content/reference/architecture-decision-log/.adr.config.json",
	"docs/content/reference/cli/**",
	"docs/data/**",
	"docs/layouts/**",
	"docs/static/.well-known/matrix/server",
	"docs/static/images/contributors/**",
	"docs/static/keys/**",
	"internal/configuration/test_resources/**",
	"internal/storage/migrations/**",
	"internal/suites/common/pki/**",
	"internal/suites/example/compose/authelia/resources/reflex.conf",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Authelia"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "web/src/components/UI/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 shadcn"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "internal/suites/testdata/fonts/LICENSE",
  "internal/suites/testdata/fonts/LiberationSans-Regular.ttf",
]
precedence = "override"
SPDX-FileCopyrightText = [
  "2010 Google Corporation",
  "2012 Red Hat, Inc.",
]
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "docs/static/images/logos/caddy.png"
precedence = "override"
SPDX-FileCopyrightText = "Stack Holdings GmbH"
SPDX-License-Identifier = "LicenseRef-Trademark"

[[annotations]]
path = "docs/static/images/logos/docker.logo.png"
precedence = "override"
SPDX-FileCopyrightText = "Docker, Inc."
SPDX-License-Identifier = "LicenseRef-Trademark"

[[annotations]]
path = "web/src/assets/images/applestore-badge.svg"
precedence = "override"
SPDX-FileCopyrightText = "Apple, Inc."
SPDX-License-Identifier = "LicenseRef-Trademark"

[[annotations]]
path = [
  "docs/static/images/logos/envoy.png",
  "docs/static/images/logos/kubernetes.png",
]
precedence = "override"
SPDX-FileCopyrightText = "The Linux Foundation"
SPDX-License-Identifier = "LicenseRef-Trademark"

[[annotations]]
path = "docs/static/images/logos/haproxy.png"
precedence = "override"
SPDX-FileCopyrightText = "HAProxy Technologies, LLC."
SPDX-License-Identifier = "LicenseRef-Trademark"

[[annotations]]
path = "docs/static/images/logos/nginx.png"
precedence = "override"
SPDX-FileCopyrightText = "F5, Inc."
SPDX-License-Identifier = "LicenseRef-Trademark"

[[annotations]]
path = "docs/static/images/logos/traefik.png"
precedence = "override"
SPDX-FileCopyrightText = "Traefik Labs"
SPDX-License-Identifier = "LicenseRef-Trademark"

[[annotations]]
path = [
  "docs/static/svgs/logos/azure.svg",
  "docs/static/svgs/logos/microsoft.svg",
]
precedence = "override"
SPDX-FileCopyrightText = "Microsoft Corporation"
SPDX-License-Identifier = "LicenseRef-Trademark"

[[annotations]]
path = [
  "docs/static/svgs/logos/goland.svg",
  "docs/static/svgs/logos/intellij-idea.svg",
  "docs/static/svgs/logos/jetbrains.svg",
  "docs/static/svgs/logos/webstorm.svg",
]
precedence = "override"
SPDX-FileCopyrightText = "JetBrains s.r.o."
SPDX-License-Identifier = "LicenseRef-Trademark"

[[annotations]]
path = [
  "docs/static/images/oid-certification.jpg",
  "docs/static/images/oid-map.png",
]
precedence = "override"
SPDX-FileCopyrightText = "OpenID Foundation"
SPDX-License-Identifier = "LicenseRef-Trademark"
