package oidc

type ClientMetadata struct {
	RedirectURIs                                    []string `json:"redirect_uris"`
	GrantTypes                                      []string `json:"grant_types,omitempty"`
	ResponseTypes                                   []string `json:"response_types,omitempty"`
	ClientName                                      string   `json:"client_name,omitempty"`
	ClientURI                                       string   `json:"client_uri,omitempty"`
	TokenEndpointAuthMethod                         string   `json:"token_endpoint_auth_method"`
	Contacts                                        []string `json:"contacts,omitempty"`
	TermsOfServiceURI                               string   `json:"tos_uri,omitempty"`
	PolicyURI                                       string   `json:"policy_uri,omitempty"`
	JSONWebKeysURI                                  string   `json:"jwks_uri,omitempty"`
	JWKS                                            bool     `json:"jwks,omitempty"`
	SoftwareID                                      string   `json:"software_id,omitempty"`
	SoftwareVersion                                 string   `json:"software_version,omitempty"`
	ClientID                                        string   `json:"client_id"`
	ClientSecret                                    string   `json:"client_secret,omitempty"`
	ClientIDIssuedAt                                int      `json:"client_id_issued_at"`
	ClientSecretExpiresAt                           int      `json:"client_secret_expires_at"`
	RegistrationAccessToken                         string   `json:"registration_access_token"`
	RegistrationClientURI                           string   `json:"registration_client_uri"`
	ApplicationType                                 string   `json:"application_type"`
	SectorIdentifierURI                             string   `json:"sector_identifier_uri"`
	SubjectType                                     string   `json:"subject_type"`
	IDTokenSignedResponseAlg                        string   `json:"id_token_signed_response_alg,omitempty"`
	IDTokenEncryptedResponseAlg                     string   `json:"id_token_encrypted_response_alg,omitempty"`
	IDTokenEncryptedResponseEnc                     string   `json:"id_token_encrypted_response_enc,omitempty"`
	UserinfoSignedResponseAlg                       string   `json:"userinfo_signed_response_alg,omitempty"`
	UserinfoEncryptedResponseAlg                    string   `json:"userinfo_encrypted_response_alg,omitempty"`
	UserinfoEncryptedResponseEnc                    string   `json:"userinfo_encrypted_response_enc,omitempty"`
	IntrospectionSignedResponseAlg                  string   `json:"introspection_signed_response_alg,omitempty"`
	IntrospectionEncryptedResponseAlg               string   `json:"introspection_encrypted_response_alg,omitempty"`
	IntrospectionEncryptedResponseEnc               string   `json:"introspection_encrypted_response_enc,omitempty"`
	RequestObjectSigningAlg                         string   `json:"request_object_signing_alg,omitempty"`
	RequestObjectEncryptionAlg                      string   `json:"request_object_encryption_alg,omitempty"`
	RequestObjectEncryptionEnc                      string   `json:"request_object_encryption_enc,omitempty"`
	TokenEndpointAuthSigningAlg                     string   `json:"token_endpoint_auth_signing_alg,omitempty"`
	DefaultMaxAge                                   int      `json:"default_max_age,omitempty"`
	RequireAuthTime                                 bool     `json:"require_auth_time,omitempty"`
	DefaultACRValues                                []string `json:"default_acr_values,omitempty"`
	InitiateLoginURI                                string   `json:"initiate_login_uri,omitempty"`
	RequestURIs                                     []string `json:"request_uris,omitempty"`
	TLSClientCertificateBoundAccessTokens           bool     `json:"tls_client_certificate_bound_access_tokens,omitempty"`
	TLSClientAuthSubjectDN                          string   `json:"tls_client_auth_subject_dn,omitempty"`
	TLSClientAuthSANDNS                             string   `json:"tls_client_auth_san_dns,omitempty"`
	TLSClientAuthSANURI                             string   `json:"tls_client_auth_san_uri,omitempty"`
	TLSClientAuthSANIP                              string   `json:"tls_client_auth_san_ip,omitempty"`
	TLSClientAuthSANEmail                           string   `json:"tls_client_auth_san_email,omitempty"`
	RequireSignedRequestObject                      bool     `json:"require_signed_request_object,omitempty"`
	RequirePushedAuthorizationRequests              bool     `json:"require_pushed_authorization_requests,omitempty"`
	FrontChannelLogoutURI                           string   `json:"front_channel_logout_uri,omitempty"`
	FrontChannelLogoutSessionRequired               bool     `json:"front_channel_logout_session_required,omitempty"`
	BackChannelLogoutURI                            string   `json:"back_channel_logout_uri,omitempty"`
	BackChannelLogoutSessionRequired                bool     `json:"back_channel_logout_session_required,omitempty"`
	PostLogoutRedirectURIs                          []string `json:"post_logout_redirect_uris,omitempty"`
	DemonstratingProofOfPossessionBoundAccessTokens bool     `json:"dpop_bound_access_tokens,omitempty"`
}
