CREATE TABLE IF NOT EXISTS users (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) DEFAULT NULL UNIQUE,
    display_name VARCHAR(100) DEFAULT NULL,
    password VARCHAR(1000) DEFAULT NULL,
    disabled INT(11) DEFAULT '0'
);
