---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: authelia
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.4-alpine
          ports:
            - containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
            periodSeconds: 1
...
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: authelia
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
...
