package expression

const (
	AttributeUserUsername                          = "username"
	AttributeUserGroups                            = "groups"
	AttributeUserDisplayName                       = "display_name"
	AttributeUserEmail                             = "email"
	AttributeUserEmails                            = "emails"
	AttributeUserEmailsExtra                       = "emails_extra"
	AttributeUserEmailVerified                     = "email_verified"
	AttributeUserGivenName                         = "given_name"
	AttributeUserMiddleName                        = "middle_name"
	AttributeUserFamilyName                        = "family_name"
	AttributeUserNickname                          = "nickname"
	AttributeUserProfile                           = "profile"
	AttributeUserPicture                           = "picture"
	AttributeUserWebsite                           = "website"
	AttributeUserGender                            = "gender"
	AttributeUserBirthdate                         = "birthdate"
	AttributeUserZoneInfo                          = "zoneinfo"
	AttributeUserLocale                            = "locale"
	AttributeUserPhoneNumber                       = "phone_number"
	AttributeUserPhoneNumberRFC3966                = "phone_number_rfc3966"
	AttributeUserPhoneExtension                    = "phone_extension"
	AttributeUserPhoneNumberVerified               = "phone_number_verified"
	AttributeUserAddress                           = "address"
	AttributeUserStreetAddress                     = "street_address"
	AttributeUserLocality                          = "locality"
	AttributeUserRegion                            = "region"
	AttributeUserPostalCode                        = "postal_code"
	AttributeUserCountry                           = "country"
	AttributeUserUpdatedAt                         = "updated_at"
	AttributeOpenIDAuthorizationRequestClaimValue  = "openid_authreq_claim_value"
	AttributeOpenIDAuthorizationRequestClaimValues = "openid_authreq_claim_values"
)
