package expression

const (
	AttributeUserUsername           = "username"
	AttributeUserGroups             = "groups"
	AttributeUserDisplayName        = "display_name"
	AttributeUserEmail              = "email"
	AttributeUserEmails             = "emails"
	AttributeUserGivenName          = "given_name"
	AttributeUserMiddleName         = "middle_name"
	AttributeUserFamilyName         = "family_name"
	AttributeUserNickname           = "nickname"
	AttributeUserProfile            = "profile"
	AttributeUserPicture            = "picture"
	AttributeUserWebsite            = "website"
	AttributeUserGender             = "gender"
	AttributeUserBirthdate          = "birthdate"
	AttributeUserZoneInfo           = "zoneinfo"
	AttributeUserLocale             = "locale"
	AttributeUserPhoneNumber        = "phone_number"
	AttributeUserPhoneNumberRFC3966 = "phone_number_rfc3966"
	AttributeUserPhoneExtension     = "phone_extension"
	AttributeUserStreetAddress      = "street_address"
	AttributeUserLocality           = "locality"
	AttributeUserRegion             = "region"
	AttributeUserPostalCode         = "postal_code"
	AttributeUserCountry            = "country"
)
