# SPDX-FileCopyrightText: 2026 Authelia
#
# SPDX-License-Identifier: Apache-2.0

---
services:
  conformance-mongodb:
    image: 'mongo:6.0.28'
    cpus: 2
    mem_limit: 2g
    networks:
      authelianet: {}

  conformance-server:
    depends_on:
      - 'conformance-mongodb'
...
