// Code generated by go generate. DO NOT EDIT.
//
// Run the following command to generate this file:
// 		go run ./cmd/authelia-gen code scripts
//

package cmd

const (
	versionSwaggerUI = "5.29.1"
)
