---
services:
  mariadb:
    image: 'mariadb:12.3.3'
    cpus: 2
    mem_limit: 1g
    environment:
      MARIADB_ROOT_PASSWORD: 'rootpassword'
      MARIADB_USER: 'admin'
      MARIADB_PASSWORD: 'password'
      MARIADB_DATABASE: 'authelia'
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: '5s'
      timeout: '10s'
      retries: 6
      start_period: '120s'
    networks:
      authelianet: {}
  authelia-backend:
    depends_on:
      mariadb:
        condition: service_healthy
...
