# yamllint disable-file

# SPDX-FileCopyrightText: 2026 Authelia
#
# SPDX-License-Identifier: Apache-2.0
---
{{- range (glob "./test_resources/config_walk/*.yml") }}
{{ fileContent . }}
{{- end }}
...
