---
certificates_directory: '/certs/'

server:
  address: 'tcp://:9091'
  tls:
    certificate: '/pki/public.backend.crt'
    key: '/pki/private.backend.pem'

log:
  level: 'debug'

identity_validation:
  reset_password:
    jwt_secret: 'unsecure_secret'

regulation:
  max_retries: 0

storage:
  encryption_key: 'a_not_so_secure_encryption_key'
  local:
    path: '/tmp/db.sqlite3'

notifier:
  filesystem:
    filename: '/tmp/notification.txt'

session:
  cookies:
    - domain: 'example.com'
      authelia_url: 'https://login.example.com:8080'
      expiration: '1 hour'
      inactivity: '5 minutes'
      remember_me: '1 year'

authentication_backend:
  file:
    path: '/config/users.yml'

totp:
  issuer: 'example.com'
  disable_reuse_security_policy: true

identity_providers:
  oidc:
    hmac_secret: 'IVPWBkAdJHje3uz7LtFTDU2pFUfh39Xm'
    jwks:
      - key: {{ secret "/pki/private.oidc.pem" | mindent 10 "|" | msquote }}
        certificate_chain: {{ secret "/pki/public.oidc.chain.pem" | mindent 10 "|" | msquote }}
    claims_policies:
      pam:
        custom_claims:
          authelia.pam.username:
            attribute: 'username'
    scopes:
      authelia.pam:
        claims:
          - 'authelia.pam.username'
    clients:
      - client_id: 'device-code'
        client_name: 'PAM Device Code Client'
        client_secret: '$pbkdf2-sha512$310000$EniFUo2z8Yjw3op3lrtuyA$xhopyOyffx2TqsQvEhoMSo1sxywIvJV8HZw/zdf62xtyryY/nkNkdcUV82r.xtd5NuyvZo7DPkOlcffM/Wvsmw'  # yamllint disable-line rule:line-length
        authorization_policy: 'two_factor'
        grant_types:
          - 'urn:ietf:params:oauth:grant-type:device_code'
        token_endpoint_auth_method: 'client_secret_post'
        claims_policy: 'pam'
        scopes:
          - 'openid'
          - 'authelia.pam'

access_control:
  default_policy: 'one_factor'
  rules:
    - domain: 'secure.example.com'
      policy: 'two_factor'
...
