---
# yaml-language-server: $schema=file:///home/james/source/repos/github.com/authelia/authelia/docs/static/schemas/v4.39/json-schema/configuration.json
theme: 'dark'
default_2fa_method: 'webauthn'
server:
  address: 'tcp://0.0.0.0:9091/'
  asset_path: ''
  buffers:
    read: 4096
    write: 4096
  timeouts:
    read: '6 seconds'
    write: '6 seconds'
    idle: '30 seconds'
  endpoints:
    enable_pprof: false
    enable_expvars: false
    authz:
      auth-request:
        implementation: 'AuthRequest'
        authn_strategies:
          - name: 'HeaderAuthRequestProxyAuthorization'
            schemes:
              - 'Basic'
            scheme_basic_cache_lifespan: 0
          - name: 'CookieSession'
            scheme_basic_cache_lifespan: 0
      ext-authz:
        implementation: 'ExtAuthz'
        authn_strategies:
          - name: 'HeaderProxyAuthorization'
            schemes:
              - 'Basic'
            scheme_basic_cache_lifespan: 0
          - name: 'CookieSession'
            scheme_basic_cache_lifespan: 0
      forward-auth:
        implementation: 'ForwardAuth'
        authn_strategies:
          - name: 'HeaderProxyAuthorization'
            schemes:
              - 'Basic'
            scheme_basic_cache_lifespan: 0
          - name: 'CookieSession'
            scheme_basic_cache_lifespan: 0
log:
  level: 'debug'
  format: 'text'
  file_path: ''
  keep_stdout: true
telemetry:
  metrics:
    enabled: false
definitions:
  network:
    LAN:
      - '10.0.0.0/16'
    k8s:
      - '10.244.0.0/16'
identity_validation:
  elevated_session:
    code_lifespan: '5 minutes'
    elevation_lifespan: '10 minutes'
    characters: 10
    require_second_factor: true
    skip_second_factor: false
  reset_password:
    jwt_lifespan: '5 minutes'
    jwt_algorithm: 'HS256'
totp:
  disable: false
  issuer: 'Authelia'
  skew: 1
  secret_size: 32
  algorithm: 'SHA1'
  digits: 6
  period: 30
  allowed_algorithms:
    - 'SHA1'
  allowed_digits:
    - 6
  allowed_periods:
    - 30
webauthn:
  disable: false
  enable_passkey_login: false
  display_name: 'Authelia'
  attestation_conveyance_preference: 'indirect'
  timeout: '60 seconds'
  filtering:
    permitted_aaguids: []
    prohibited_aaguids: []
    prohibit_backup_eligibility: false
  selection_criteria:
    attachment: ''
    discoverability: 'preferred'
    user_verification: 'preferred'
  metadata:
    enabled: false
    validate_trust_anchor: true
    validate_entry: true
    validate_entry_permit_zero_aaguid: false
    validate_status: true
    validate_status_permitted: []
    validate_status_prohibited: []
ntp:
  address: 'udp://1.1.1.1:123'
  version: 3
  max_desync: '3 seconds'
  disable_startup_check: false
  disable_failure: false
authentication_backend:
  password_reset:
    disable: false
    custom_url: ''
  password_change:
    disable: false
  ldap:
    implementation: 'custom'
    address: 'ldap://openldap.auth:389'
    timeout: '5 seconds'
    start_tls: false
    tls:
      server_name: ''
      skip_verify: false
      minimum_version: 'TLS1.2'
      maximum_version: 'TLS1.3'
    pooling:
      enable: false
      count: 5
      retries: 2
      timeout: '10 seconds'
    base_dn: 'dc=example,dc=com'
    additional_users_dn: 'ou=users'
    users_filter: '(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))'
    additional_groups_dn: 'ou=groups'
    groups_filter: '(&(member={dn})(objectclass=groupOfNames))'
    group_search_mode: 'filter'
    permit_referrals: true
    permit_unauthenticated_bind: false
    permit_feature_detection_failure: false
    user: 'cn=bind_authelia,ou=services,dc=example,dc=com'
    attributes:
      distinguished_name: 'distinguishedName'
      username: 'uid'
      display_name: 'displayName'
      family_name: ''
      given_name: ''
      middle_name: ''
      nickname: ''
      gender: ''
      birthdate: ''
      website: ''
      profile: ''
      picture: ''
      zoneinfo: ''
      locale: ''
      phone_number: ''
      phone_extension: ''
      street_address: ''
      locality: ''
      region: ''
      postal_code: ''
      country: ''
      mail:  'mail'
      member_of:  'memberOf'
      group_name:  'cn'
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: false
    require_lowercase: false
    require_number: false
    require_special: false
  zxcvbn:
    enabled: false
    min_score: 0
session:
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5 minutes'
  expiration: '1 hour'
  remember_me: '1 month'
  cookies:
    - domain: 'example.com'
      authelia_url: 'https://example.com'
      name: 'authelia_session'
      inactivity: '5 minutes'
      expiration: '1 hour'
      remember_me: '2 month'
  redis:
    host: 'authelia-redis.auth'
    port: 6379
    username: 'default'
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0
regulation:
  modes:
    - 'user'
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'
storage:
  postgres:
    address: 'tcp://authelia-postgres-rw.database:5432'
    servers: []
    timeout: '5 seconds'
    database: 'authelia'
    schema: 'public'
    username: 'authelia'
notifier:
  disable_startup_check: false
  smtp:
    address: 'submissions://docker-mailserver.email:465'
    timeout: '5 seconds'
    username: 'hello@example.com'
    sender: 'Authelia <hello@example.com>'
    identifier: 'example.com'
    subject: '[Authelia] {title}'
    startup_check_address: 'test@authelia.com'
    disable_html_emails: false
    disable_require_tls: false
    disable_starttls: false
    tls:
      server_name: 'authelia.example.com'
      skip_verify: false
      minimum_version: 'TLS1.2'
      maximum_version: 'TLS1.3'
identity_providers:
  oidc:
    lifespans:
      access_token: '1 hour'
      authorize_code: '1 minute'
      id_token: '1 hour'
      refresh_token: '1 hour and 30 minutes'
    enforce_pkce: 'public_clients_only'
    enable_pkce_plain_challenge: false
    enable_client_debug_messages: false
    enable_jwt_access_token_stateless_introspection: false
    minimum_parameter_entropy: 8
    discovery_signed_response_alg: ''
    discovery_signed_response_key_id: ''
    require_pushed_authorization_requests: false
    jwks:
      - algorithm: 'RS256'
        use: 'sig'
        key_id: 'default'
        key: |
          -----BEGIN PRIVATE KEY-----
          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDXPT1xV9z05l4k
          X0h+uryEe/gT7tQlg97m9qIXHbCBh6d4sGsA7JGKelDxarcrMa+PPUPKYlMTh/Ar
          3pPFU5+qjNrbphhAirM6djfQ/WRxZtLn1/BMyT/qCapEvAWV7uT4VUOD/E9v1Ya+
          qUAiMKzuEJKfDShRO4b6bDHK9mtn2n5nVZ40Qdkp4Uv/JwrzwsdoRePxbY+9Lpf2
          qvHjkJowDVo3HL0g4p3Ze2AqDORYbdWuYTASwJPV7ricfpBhW6iWc+3CdeeF0LBY
          yuhO4/Uu2exZEEh+sdE+2mdBl1fsSev8AoREuuF5d1gex+6x4CZNU54EUpVjRMSR
          d28h7BPLAgMBAAECggEALTUio5zFvvZnzZHpwxxrnhP/rggarOp+tdoVf29v9DTO
          2w2K2/3UL9azC5HTeRINgrNmeqqeMlr5+ezc8rQ2s/azvTCspVm8fUn5PT8LiroD
          EEkNosMeVoTDK36mWbB8jSAzdxRWhvG9RGx+GPBKUhJPCXMVBcLP/ecdqjiJpJ0g
          FhcHc6bXgQuK2muC84JUMbk+Z+jdw3iPxKQdyWwj2M9EYUAbl5905aWSwmCVal20
          xC4l3G9ihqFmxEUchNmbvc9W/KpQujleV40yNDZPwd/FJJUyuGgrWvqplvEGmWXm
          rrqyMps0ELe1a6gz3as8hPt9zyeCKjYOAEZe6eSQCQKBgQDraHiz7KDluNzCOygi
          tZJETp1GFL3uIPqwZFH42VdwQqdmc+6GxE19NtdaEtUrjybJ5zCUxUC9bYclF+hb
          1mrDS6ZFND3IuKJbBJJwrOAcIs64JEU623MIYuH92jnklety/kHKWVzK6fwcFYPf
          qiKQADCRCj9BJaPRbwI/fJN2/QKBgQDqER+6MQugJMP32OSaVgIY58CbA4NuH/s7
          e0nOvQGWmIPtsJxaHJ+bZejr4x5br6W5tSuMGO/ovrzEC8IssfT+q6jgJQFcXnwL
          GzVBIinczOTkVx5Y/C6zrGpLbmu5QfByLDQNmrN1ZIF/2xzmggBQFxdbQxD608i1
          RZnSCaxEZwKBgQC6F/xTP9xxvZHGeb1gsujN1te9bug2Nxv2FVg3wJi+xfJPq5YE
          M2qOcawMKJcbuC6RrZFaChUDqnILgLrO3tHHUSY/zuyIoGy4RwT8zazckSeZqhKQ
          VKq7FnBQnRLnARz/6r9Xlw0j25TRHrEBPx3TeFLsVY1rkrXN+lNsnK52gQKBgHOu
          fuXAs6Q0R35I/cKhW2v/rhtuwxg8Sih9qF663vwU6K8iqEOI/gEJfvKGT0y1JM0B
          k0IsWPXIvvaNcSwxz4nGQTJ2V5PVRq0eh1VnkxUDVuTbga4tBM/cGLSrICZxRmrH
          GfrXSHZuc+pC2qe5/HmYz/xUyyGMZhfhDELYcQFlAoGAMZUtoP1X5FqVvu+1CXXo
          URExPgJUy7bw9+lcPx33mwCJtwF+XLP2oSAkvV1D4WW+hvugINPil2mvilA9cVHh
          sbH8Lo6+GPXE+MXrt5EmlVBwGD8a2Jvn//lhC31zs7GzJ1z2QuKDXhqQxmzkUpmo
          cM39KyeVRH8j4BNrtmuzU/A=
          -----END PRIVATE KEY-----
    cors:
      allowed_origins_from_client_redirect_uris: false
access_control:
  default_policy: 'deny'
  rules:
    - policy: two_factor
      domain:
        - '*.example.com'
      subject:
        - ['group:admins']
...
