---
services:
  authelia-backend:
    volumes:
      - './ActiveDirectory/configuration.yml:/config/configuration.yml'
      - './common/pki:/pki'
      - './common/pki/public.crt:/pki/public/public.crt'
...
