package templates

import (
	"text/template"
)

// EmailBasicPlainText the template of email that the user will receive for identity verification.
var EmailBasicPlainText *template.Template

func init() {
	t, err := template.New("text_email_template_basic").Parse(emailContentBasicPlainText)
	if err != nil {
		panic(err)
	}

	EmailBasicPlainText = t
}

const emailContentBasicPlainText = `
Your password has been successfully reset.
If you did not initiate the process your credentials might have been compromised. You should reset your password and contact an administrator.

This email was generated by a user with the IP {{.remoteIP}}.

Please contact an administrator if you did not initiate the process.
`
