#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" buildkite
usermod -o -u "$PUID" buildkite

cat <<'EOF'
--------------------------------------------
   / \  _   _| |_| |__   ___| (_) __ _
  / _ \| | | | __| '_ \ / _ \ | |/ _` |
 / ___ \ |_| | |_| | | |  __/ | | (_| |
/_/   \_\__,_|\__|_| |_|\___|_|_|\__,_|
                ____ ___
               / ___|_ _|
              | |    | |
              | |___ | |
               \____|___|
--------------------------------------------
GID/UID
--------------------------------------------
EOF
echo "
User uid:    $(id -u buildkite)
User gid:    $(id -g buildkite)
--------------------------------------------
"
chown buildkite:buildkite /buildkite