#!/usr/bin/env bash
set +u

git fetch -q

if [[ ! "${BUILDKITE_COMMAND}" =~ ^\.buildkite/pipeline.sh ]]; then
  echo "--- :buildkite: Setting up Build environment"
  source bootstrap.sh

  if [[ "${BUILDKITE_LABEL}" == ":hammer_and_wrench: Unit Test" ]] || [[ "${BUILDKITE_LABEL}" =~ :selenium: ]]; then
    go mod download
  fi
fi
