#!/usr/bin/env bash

set +u

if [[ ! "${BUILDKITE_COMMAND}" =~ buildkite-agent\ pipeline\ upload ]] && \
[[ "${BUILDKITE_AGENT_META_DATA_CLEANBUILD}" != "false" ]]; then
  echo "--- :docker: Clean environment"
  docker images --filter "label=org.authelia.image.prune.protection=true" -q | xargs -r -I{} docker run -d --name "protect_{}" {} sleep infinity; docker system prune -af; docker ps -aq --filter "name=protect_" | xargs -r docker rm -f
fi

sudo find /tmp/ ! -wholename "/tmp/" ! -wholename "/tmp/buildkite-agent-hook-wrapper*" ! -name "buildkite*" ! -name "job-env-*" -type d,f -exec rm -rf {} +
