#!/bin/bash

set +u

if [[ $BUILDKITE_COMMAND == ".buildkite/steps/buildandtest.sh" ]];
then
    tar -czf dist.tar.gz dist
    tar -czf web.tar.gz web
fi

if [[ $BUILDKITE_LABEL =~ ":docker: Build" && BUILDKITE_TAG != "" ]];
then
  echo "--- :docker: Saving artifacts for :github: releases"
  docker create --name authelia-binary nightah/authelia:${BUILDKITE_TAG:1}-$ARCH
  docker cp authelia-binary:/usr/app/authelia ./authelia-linux-$ARCH
  docker cp authelia-binary:/usr/app/public_html ./
  docker rm -f authelia-binary
  tar -czf authelia-linux-$ARCH.tar.gz authelia-linux-$ARCH public_html
  sha256sum authelia-linux-$ARCH.tar.gz > authelia-linux-$ARCH.tar.gz.sha256
fi