#!/bin/bash

set +u

if [[ $BUILDKITE_LABEL =~ ":selenium:" ]];
then
  DEFAULT_ARCH=amd64
  echo "--- :twisted_rightwards_arrows::desktop_computer: Downloading build artifacts"
  buildkite-agent artifact download "authelia-image-${DEFAULT_ARCH}*" .
  zstdcat authelia-image-${DEFAULT_ARCH}.tar.zst | docker load
  docker tag authelia/authelia authelia:dist
fi

if [[ $BUILDKITE_LABEL =~ ":docker: Deploy Image" ]];
then
  buildkite-agent artifact download "authelia-image-${ARCH}*" .
  zstdcat authelia-image-"${ARCH}".tar.zst | docker load
fi

if [[ $BUILDKITE_LABEL == ":github: Deploy Artifacts" ]];
then
  buildkite-agent artifact download "authelia-linux-*" .
fi