#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2019 Authelia
#
# SPDX-License-Identifier: Apache-2.0

set +u

if [[ ! "${BUILDKITE_COMMAND}" =~ "buildkite-agent pipeline upload" ]] && \
[[ "${BUILDKITE_AGENT_META_DATA_CLEANBUILD}" != "false" ]]; then
  echo "--- :docker: Clean environment"
  docker system prune -af --volumes
fi

sudo find /tmp/ ! -wholename "/tmp/" ! -name "buildkite*" ! -name "job-env-*" -type d,f -exec rm -rf {} +
