#!/bin/bash

set -e

source bootstrap.sh

docker --version
docker-compose --version
echo "node `node -v`"
echo "npm `npm -v`"

authelia-scripts bootstrap

docker-compose -f docker-compose.yml \
  -f example/compose/mongo/docker-compose.yml \
  -f example/compose/redis/docker-compose.yml \
  -f example/compose/nginx/portal/docker-compose.yml \
  -f example/compose/smtp/docker-compose.yml \
  -f example/compose/httpbin/docker-compose.yml \
  -f example/compose/ldap/docker-compose.admin.yml \
  -f example/compose/ldap/docker-compose.yml \
  pull

# Build
authelia-scripts build

# Run unit tests
authelia-scripts unittest

# Build the docker image
authelia-scripts docker build

# Run integration tests
authelia-scripts suites test --headless

# Test npm deployment before actual deployment
# ./scripts/npm-deployment-test.sh
