#!/bin/bash

set -e

export PATH=./scripts:$PATH

docker --version
docker-compose --version
echo "node `node -v`"
echo "npm `npm -v`"

# Build
authelia-scripts build

# Run unit tests
authelia-scripts unittest

# Build the docker image
authelia-scripts docker build

# Run integration tests
authelia-scripts suites test --headless

# Test npm deployment before actual deployment
# ./scripts/npm-deployment-test.sh
