#!/bin/bash

set -x
set -e

DIST_DIR=dist

rm -rf $DIST_DIR
mkdir -p $DIST_DIR

GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o $DIST_DIR/authelia

# Build the client
pushd client
npm run build
popd

mv client/build $DIST_DIR/public_html

