#!/usr/bin/env node

var { exec } = require('./utils/exec');
var { IMAGE_NAME, DOCKERHUB_IMAGE_NAME } = require('./utils/docker');

async function main() {
  await exec(`docker build -t ${IMAGE_NAME}:dist .`);
  await exec(`docker tag ${IMAGE_NAME}:dist ${DOCKERHUB_IMAGE_NAME}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
})