---
services:
  zoraxy:
    # build: ./example/compose/caddy/ # used for debugging
    image: caddy:2.9.1-alpine
    volumes:
      - './example/compose/zoraxy/zoraxy.conf:/etc/caddy/Caddyfile'
      - './common/pki:/pki'
    networks:
      authelianet:
        ipv4_address: 192.168.240.100
...
