---
# Default config
tabWidth: 2
embeddedLanguageFormatting: "off"
endOfLine: lf
singleQuote: false
printWidth: 100000
trailingComma: all
bracketSameLine: true
quoteProps: consistent
experimentalTernaries: true

# Overridden config
overrides:
  - files: ["*.json"]
    options:
      printWidth: 1
...
