---
services:
  smtp:
    image: 'axllent/mailpit:v1.31.0'
    cpus: 2
    mem_limit: 1g
    volumes:
      - './common/pki:/pki'
    environment:
      GOMAXPROCS: '2'
      MP_SMTP_TLS_CERT: '/pki/public.crt'
      MP_SMTP_TLS_KEY: '/pki/private.pem'
      MP_SMTP_AUTH_ACCEPT_ANY: '1'
    labels:
      traefik.frontend.rule: 'Host:mail.example.com'
      traefik.port: '8025'
      traefik.enable: 'true'
      traefik.http.routers.mail.rule: 'Host(`mail.example.com`)'
      traefik.http.routers.mail.entrypoints: 'https'
      traefik.http.routers.mail.tls: 'true'
      traefik.http.services.mail.loadbalancer.server.port: '8025'
    healthcheck:
      test: ['CMD-SHELL', 'nc -z 127.0.0.1 1025 && /mailpit readyz || exit 1']
      interval: '5s'
      timeout: '10s'
      retries: 6
      start_period: '120s'
    networks:
      authelianet:
        aliases:
          - 'mail.example.com'
  authelia-backend:
    depends_on:
      smtp:
        condition: service_healthy
...
