FROM alpine:3.22.0@sha256:8a1f59ffb675680d47db6337b49d22281a139e9d709335b492be023728e11715

RUN \
echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories && \
apk add --no-cache \
	bash \
	krb5@edge \
	openldap-clients@edge \
	openssl \
	samba-dc@edge \
	supervisor

CMD ["/init.sh", "setup"]
