#!/bin/bash

set -e

appSetup () {

  # Set variables
  DOMAIN=${DOMAIN:-SAMDOM.LOCAL}
  DOMAINPASS=${DOMAINPASS:-youshouldsetapassword}
  NOCOMPLEXITY=${NOCOMPLEXITY:-false}
  INSECURELDAP=${INSECURELDAP:-false}

  UDOMAIN=${DOMAIN^^}
  URDOMAIN=${UDOMAIN%%.*}

  # Set up samba
  mv /etc/krb5.conf /etc/krb5.conf.orig
  cat > /etc/krb5.conf <<EOF
[libdefaults]
    dns_lookup_realm = false
    dns_lookup_kdc = true
    default_realm = ${UDOMAIN}
EOF
  # If the finished file isn't there, this is brand new, we're not just moving to a new container
  if [[ ! -f /etc/samba/external/smb.conf ]]; then
    mv /etc/samba/smb.conf /etc/samba/smb.conf.orig
    samba-tool domain provision --use-rfc2307 --domain="${URDOMAIN}" --realm="${UDOMAIN}" --server-role=dc --dns-backend=SAMBA_INTERNAL --adminpass="${DOMAINPASS}"
    if [[ ${NOCOMPLEXITY,,} == "true" ]]; then
      samba-tool domain passwordsettings set --complexity=off
      samba-tool domain passwordsettings set --history-length=0
      samba-tool domain passwordsettings set --min-pwd-length=3
      samba-tool domain passwordsettings set --min-pwd-age=0
      samba-tool domain passwordsettings set --max-pwd-age=0
    fi
    sed -i "/\[global\]/a \
      \\\tidmap_ldb:use rfc2307 = yes\\n\
      wins support = yes\\n\
      template shell = /bin/bash\\n\
      winbind nss info = rfc2307\\n\
      idmap config ${URDOMAIN}: range = 10000-20000\\n\
      idmap config ${URDOMAIN}: backend = ad\\n\
      dsdb:schema update allowed = yes\
      " /etc/samba/smb.conf
    if [[ ${INSECURELDAP,,} == "true" ]]; then
      sed -i "/\[global\]/a \
        \\\tldap server require strong auth = no\
        " /etc/samba/smb.conf
    fi
    cd /var/lib/samba/private/tls
    openssl req -x509 -nodes -newkey rsa:4096 -keyout ca-key.pem -days 365 -out ca.pem -subj '/O=Samba Administration/OU=Samba - temporary autogenerated CA certificate/CN=LDAP.example.com'
    openssl req -x509 -nodes -CA ca.pem -CAkey ca-key.pem -newkey rsa:4096 -keyout key.pem -days 365 -out cert.pem -subj '/O=Samba Administration/OU=Samba - temporary autogenerated HOST certificate/CN=LDAP.example.com'
    # shellcheck disable=SC2153
    DOMAIN_DN="DC=${LDOMAIN//./,DC=}"
    if [[ -f /schema-attributes.ldif ]]; then
      sed "s/DC=X/${DOMAIN_DN}/g" /schema-attributes.ldif > /tmp/schema-attributes-ready.ldif
      LDB_MODULES_PATH=/usr/lib/samba/ldb ldbadd -H /var/lib/samba/private/sam.ldb /tmp/schema-attributes-ready.ldif -o "dsdb:schema update allowed=true" && echo "Schema attributes loaded successfully" || echo "Schema attributes loading failed"
    fi
    if [[ -f /schema-classes.ldif ]]; then
      sed "s/DC=X/${DOMAIN_DN}/g" /schema-classes.ldif > /tmp/schema-classes-ready.ldif
      LDB_MODULES_PATH=/usr/lib/samba/ldb ldbadd -H /var/lib/samba/private/sam.ldb /tmp/schema-classes-ready.ldif -o "dsdb:schema update allowed=true" && echo "Schema classes loaded successfully" || echo "Schema classes loading failed"
    fi

    # Once we are set up, we'll make a file so that we know to use it if we ever spin this up again
    mkdir -p /etc/samba/external
    cp /etc/samba/smb.conf /etc/samba/external/smb.conf
  else
    cp /etc/samba/external/smb.conf /etc/samba/smb.conf
  fi

  # Set up supervisor
  mkdir /etc/supervisor.d/
  mkdir /etc/supervisor.d/
  cat > /etc/supervisor.d/supervisord.ini <<EOF
[supervisord]
nodaemon=true

[program:samba]
command=/usr/sbin/samba -i

[program:provision]
command=/bin/sh -c 'sleep 5 && /provision.sh'
environment=LDOMAIN="${LDOMAIN}",DOMAINPASS="${DOMAINPASS}"
autorestart=false
startsecs=0
EOF

  cat > /provision.sh <<'PROVISION_SCRIPT'
#!/bin/bash
set -e

until samba-tool user show administrator >/dev/null 2>&1; do
  sleep 1
done

if [[ -f /schema-extensions.ldif ]]; then
  DOMAIN_DN="DC=${LDOMAIN//./,DC=}"
  sed "s/DC=X/${DOMAIN_DN}/g" /schema-extensions.ldif > /tmp/schema-extensions-ready.ldif
  ldbadd -H /var/lib/samba/private/sam.ldb /tmp/schema-extensions-ready.ldif -o "dsdb:schema update allowed=true" || echo "Schema extension loading failed"
fi

samba-tool user setpassword administrator --newpassword=password
samba-tool ou create "OU=Users"
samba-tool ou create "OU=Groups"
samba-tool group add dev --groupou=OU=Groups
samba-tool group add admins --groupou=OU=Groups
samba-tool group add authelia-admin --groupou=OU=Groups
samba-tool user create john password --userou=OU=Users --use-username-as-cn --given-name John --surname Doe --mail-address john.doe@authelia.com
samba-tool user create harry password --userou=OU=Users --use-username-as-cn --given-name Harry --surname Potter --mail-address harry.potter@authelia.com
samba-tool user create bob password --userou=OU=Users --use-username-as-cn --given-name Bob --surname Dylan --mail-address bob.dylan@authelia.com
samba-tool user create james password --userou=OU=Users --use-username-as-cn --given-name James --surname Dean --mail-address james.dean@authelia.com
samba-tool group addmembers "dev" john,bob
samba-tool group addmembers "admins" john
samba-tool group addmembers "authelia-admin" john
PROVISION_SCRIPT

  chmod +x /provision.sh

  appStart
}

appStart () {
  /usr/bin/supervisord
}


case "${1}" in
  start)
    if [[ -f /etc/samba/external/smb.conf ]]; then
      cp /etc/samba/external/smb.conf /etc/samba/smb.conf
      appStart
    else
    	echo "Config file is missing."
    fi
    ;;
  setup)
    # If the supervisor conf isn't there, we're spinning up a new container
    if [[ -f /etc/supervisor.d/supervisord.ini ]]; then
      appStart
    else
      appSetup
    fi
    ;;
esac

exit 0
