# Only include files needed for the PAM suite build.
*

!go.mod
!go.sum
!cmd/authelia-pam/
!extras/pam/src/*.c
!extras/pam/src/*.h
!extras/pam/Makefile
!internal/suites/example/compose/pam/entrypoint.sh
