// SPDX-FileCopyrightText: 2026 Authelia
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by go generate. DO NOT EDIT.
//
// Run the following command to generate this file:
// 		go run ./cmd/authelia-gen code keys
//

export default {
    defaultIgnores: true,
    extends: ["@commitlint/config-conventional"],
    helpUrl: "https://www.authelia.com/contributing/guidelines/commit-message/",
    rules: {
        "body-max-line-length": [2, "always", "Infinity"],
        "body-min-length": [2, "always", 20],
        "header-case": [2, "always", "lower-case"],
        "header-max-length": [2, "always", 72],
        "scope-enum": [
            2,
            "always",
            [
                "api",
                "autheliabot",
                "authentication",
                "authorization",
                "buildkite",
                "bundler",
                "clock",
                "cmd",
                "codecov",
                "commands",
                "configuration",
                "deps",
                "docker",
                "duo",
                "expression",
                "go",
                "golangci-lint",
                "handlers",
                "lefthook",
                "logging",
                "metrics",
                "middlewares",
                "mocks",
                "model",
                "notification",
                "npm",
                "ntp",
                "oidc",
                "random",
                "regulation",
                "renovate",
                "reviewdog",
                "server",
                "service",
                "session",
                "storage",
                "suites",
                "systemd",
                "templates",
                "totp",
                "utils",
                "web",
                "webauthn",
            ],
        ],
        "type-enum": [
            2,
            "always",
            ["build", "ci", "docs", "feat", "fix", "i18n", "perf", "refactor", "release", "revert", "test"],
        ],
    },
};
