allowBuilds:
  lefthook: true
  unrs-resolver: true
overrides:
  fast-uri: 4.1.3
  js-yaml: 5.4.0
  minimatch: 10.2.6
  picomatch: 4.0.7
  semver: 7.8.5
  vite: 8.2.2
peerDependencyRules:
  allowedVersions:
    "@types/react": "19"
    eslint: "10"
    react: "19"
    react-dom: "19"
